// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface ColOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.Col)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Message.Side side = 1;</code>
   * @return A list containing the side.
   */
  java.util.List<proto.Side> getSideList();
  /**
   * <code>repeated .Message.Side side = 1;</code>
   * @return The count of side.
   */
  int getSideCount();
  /**
   * <code>repeated .Message.Side side = 1;</code>
   * @param index The index of the element to return.
   * @return The side at the given index.
   */
  proto.Side getSide(int index);
  /**
   * <code>repeated .Message.Side side = 1;</code>
   * @return A list containing the enum numeric values on the wire for side.
   */
  java.util.List<java.lang.Integer>
  getSideValueList();
  /**
   * <code>repeated .Message.Side side = 1;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of side at the given index.
   */
  int getSideValue(int index);
}
