// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsError)
    com.google.protobuf.MessageOrBuilder {
}
