// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsGameStartPushOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsGameStartPush)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 黑子，白子
   * </pre>
   *
   * <code>.Message.Side side = 1;</code>
   * @return The enum numeric value on the wire for side.
   */
  int getSideValue();
  /**
   * <pre>
   * 黑子，白子
   * </pre>
   *
   * <code>.Message.Side side = 1;</code>
   * @return The side.
   */
  proto.Side getSide();

  /**
   * <pre>
   * 开始时间 ms
   * </pre>
   *
   * <code>int64 startTime = 2;</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <pre>
   * 回合时间 ms
   * </pre>
   *
   * <code>int64 roundTime = 3;</code>
   * @return The roundTime.
   */
  long getRoundTime();

  /**
   * <pre>
   * 可悔棋次数
   * </pre>
   *
   * <code>int32 revertCount = 5;</code>
   * @return The revertCount.
   */
  int getRevertCount();

  /**
   * <pre>
   * 悔棋时间
   * </pre>
   *
   * <code>int64 revertTime = 6;</code>
   * @return The revertTime.
   */
  long getRevertTime();

  /**
   * <pre>
   * 认输回合
   * </pre>
   *
   * <code>int32 surrenderRound = 7;</code>
   * @return The surrenderRound.
   */
  int getSurrenderRound();
}
