// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

/**
 * <pre>
 * msgNo: -107
 * </pre>
 *
 * Protobuf type {@code Message.FsGameStatusRes}
 */
public  final class FsGameStatusRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message.FsGameStatusRes)
    FsGameStatusResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FsGameStatusRes.newBuilder() to construct.
  private FsGameStatusRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FsGameStatusRes() {
    side_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FsGameStatusRes();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FsGameStatusRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            side_ = rawValue;
            break;
          }
          case 16: {

            startTime_ = input.readInt64();
            break;
          }
          case 24: {

            roundTime_ = input.readInt64();
            break;
          }
          case 40: {

            revertCount_ = input.readInt32();
            break;
          }
          case 48: {

            myTurn_ = input.readBool();
            break;
          }
          case 64: {

            end_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Gobang.internal_static_Message_FsGameStatusRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Gobang.internal_static_Message_FsGameStatusRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.FsGameStatusRes.class, proto.FsGameStatusRes.Builder.class);
  }

  public static final int SIDE_FIELD_NUMBER = 1;
  private int side_;
  /**
   * <pre>
   * 黑子，白子
   * </pre>
   *
   * <code>.Message.Side side = 1;</code>
   * @return The enum numeric value on the wire for side.
   */
  public int getSideValue() {
    return side_;
  }
  /**
   * <pre>
   * 黑子，白子
   * </pre>
   *
   * <code>.Message.Side side = 1;</code>
   * @return The side.
   */
  public proto.Side getSide() {
    @SuppressWarnings("deprecation")
    proto.Side result = proto.Side.valueOf(side_);
    return result == null ? proto.Side.UNRECOGNIZED : result;
  }

  public static final int STARTTIME_FIELD_NUMBER = 2;
  private long startTime_;
  /**
   * <pre>
   * 开始时间 ms
   * </pre>
   *
   * <code>int64 startTime = 2;</code>
   * @return The startTime.
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int ROUNDTIME_FIELD_NUMBER = 3;
  private long roundTime_;
  /**
   * <pre>
   * 回合剩余时间 ms
   * </pre>
   *
   * <code>int64 roundTime = 3;</code>
   * @return The roundTime.
   */
  public long getRoundTime() {
    return roundTime_;
  }

  public static final int REVERTCOUNT_FIELD_NUMBER = 5;
  private int revertCount_;
  /**
   * <pre>
   * 可悔棋次数
   * </pre>
   *
   * <code>int32 revertCount = 5;</code>
   * @return The revertCount.
   */
  public int getRevertCount() {
    return revertCount_;
  }

  public static final int MYTURN_FIELD_NUMBER = 6;
  private boolean myTurn_;
  /**
   * <pre>
   * 是否我的回合
   * </pre>
   *
   * <code>bool myTurn = 6;</code>
   * @return The myTurn.
   */
  public boolean getMyTurn() {
    return myTurn_;
  }

  public static final int END_FIELD_NUMBER = 8;
  private boolean end_;
  /**
   * <pre>
   * 游戏是否结束
   * </pre>
   *
   * <code>bool end = 8;</code>
   * @return The end.
   */
  public boolean getEnd() {
    return end_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (side_ != proto.Side.NONE.getNumber()) {
      output.writeEnum(1, side_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(2, startTime_);
    }
    if (roundTime_ != 0L) {
      output.writeInt64(3, roundTime_);
    }
    if (revertCount_ != 0) {
      output.writeInt32(5, revertCount_);
    }
    if (myTurn_ != false) {
      output.writeBool(6, myTurn_);
    }
    if (end_ != false) {
      output.writeBool(8, end_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (side_ != proto.Side.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, side_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, startTime_);
    }
    if (roundTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, roundTime_);
    }
    if (revertCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, revertCount_);
    }
    if (myTurn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, myTurn_);
    }
    if (end_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, end_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.FsGameStatusRes)) {
      return super.equals(obj);
    }
    proto.FsGameStatusRes other = (proto.FsGameStatusRes) obj;

    if (side_ != other.side_) return false;
    if (getStartTime()
        != other.getStartTime()) return false;
    if (getRoundTime()
        != other.getRoundTime()) return false;
    if (getRevertCount()
        != other.getRevertCount()) return false;
    if (getMyTurn()
        != other.getMyTurn()) return false;
    if (getEnd()
        != other.getEnd()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIDE_FIELD_NUMBER;
    hash = (53 * hash) + side_;
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + ROUNDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRoundTime());
    hash = (37 * hash) + REVERTCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRevertCount();
    hash = (37 * hash) + MYTURN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMyTurn());
    hash = (37 * hash) + END_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnd());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.FsGameStatusRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsGameStatusRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsGameStatusRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsGameStatusRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsGameStatusRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsGameStatusRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsGameStatusRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.FsGameStatusRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.FsGameStatusRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.FsGameStatusRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.FsGameStatusRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.FsGameStatusRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.FsGameStatusRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * msgNo: -107
   * </pre>
   *
   * Protobuf type {@code Message.FsGameStatusRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message.FsGameStatusRes)
      proto.FsGameStatusResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Gobang.internal_static_Message_FsGameStatusRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Gobang.internal_static_Message_FsGameStatusRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.FsGameStatusRes.class, proto.FsGameStatusRes.Builder.class);
    }

    // Construct using proto.FsGameStatusRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      side_ = 0;

      startTime_ = 0L;

      roundTime_ = 0L;

      revertCount_ = 0;

      myTurn_ = false;

      end_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Gobang.internal_static_Message_FsGameStatusRes_descriptor;
    }

    @java.lang.Override
    public proto.FsGameStatusRes getDefaultInstanceForType() {
      return proto.FsGameStatusRes.getDefaultInstance();
    }

    @java.lang.Override
    public proto.FsGameStatusRes build() {
      proto.FsGameStatusRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.FsGameStatusRes buildPartial() {
      proto.FsGameStatusRes result = new proto.FsGameStatusRes(this);
      result.side_ = side_;
      result.startTime_ = startTime_;
      result.roundTime_ = roundTime_;
      result.revertCount_ = revertCount_;
      result.myTurn_ = myTurn_;
      result.end_ = end_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.FsGameStatusRes) {
        return mergeFrom((proto.FsGameStatusRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.FsGameStatusRes other) {
      if (other == proto.FsGameStatusRes.getDefaultInstance()) return this;
      if (other.side_ != 0) {
        setSideValue(other.getSideValue());
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getRoundTime() != 0L) {
        setRoundTime(other.getRoundTime());
      }
      if (other.getRevertCount() != 0) {
        setRevertCount(other.getRevertCount());
      }
      if (other.getMyTurn() != false) {
        setMyTurn(other.getMyTurn());
      }
      if (other.getEnd() != false) {
        setEnd(other.getEnd());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.FsGameStatusRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.FsGameStatusRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int side_ = 0;
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @return The enum numeric value on the wire for side.
     */
    public int getSideValue() {
      return side_;
    }
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @param value The enum numeric value on the wire for side to set.
     * @return This builder for chaining.
     */
    public Builder setSideValue(int value) {
      side_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @return The side.
     */
    public proto.Side getSide() {
      @SuppressWarnings("deprecation")
      proto.Side result = proto.Side.valueOf(side_);
      return result == null ? proto.Side.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @param value The side to set.
     * @return This builder for chaining.
     */
    public Builder setSide(proto.Side value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      side_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSide() {
      
      side_ = 0;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <pre>
     * 开始时间 ms
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @return The startTime.
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <pre>
     * 开始时间 ms
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 开始时间 ms
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long roundTime_ ;
    /**
     * <pre>
     * 回合剩余时间 ms
     * </pre>
     *
     * <code>int64 roundTime = 3;</code>
     * @return The roundTime.
     */
    public long getRoundTime() {
      return roundTime_;
    }
    /**
     * <pre>
     * 回合剩余时间 ms
     * </pre>
     *
     * <code>int64 roundTime = 3;</code>
     * @param value The roundTime to set.
     * @return This builder for chaining.
     */
    public Builder setRoundTime(long value) {
      
      roundTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 回合剩余时间 ms
     * </pre>
     *
     * <code>int64 roundTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoundTime() {
      
      roundTime_ = 0L;
      onChanged();
      return this;
    }

    private int revertCount_ ;
    /**
     * <pre>
     * 可悔棋次数
     * </pre>
     *
     * <code>int32 revertCount = 5;</code>
     * @return The revertCount.
     */
    public int getRevertCount() {
      return revertCount_;
    }
    /**
     * <pre>
     * 可悔棋次数
     * </pre>
     *
     * <code>int32 revertCount = 5;</code>
     * @param value The revertCount to set.
     * @return This builder for chaining.
     */
    public Builder setRevertCount(int value) {
      
      revertCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 可悔棋次数
     * </pre>
     *
     * <code>int32 revertCount = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevertCount() {
      
      revertCount_ = 0;
      onChanged();
      return this;
    }

    private boolean myTurn_ ;
    /**
     * <pre>
     * 是否我的回合
     * </pre>
     *
     * <code>bool myTurn = 6;</code>
     * @return The myTurn.
     */
    public boolean getMyTurn() {
      return myTurn_;
    }
    /**
     * <pre>
     * 是否我的回合
     * </pre>
     *
     * <code>bool myTurn = 6;</code>
     * @param value The myTurn to set.
     * @return This builder for chaining.
     */
    public Builder setMyTurn(boolean value) {
      
      myTurn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否我的回合
     * </pre>
     *
     * <code>bool myTurn = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMyTurn() {
      
      myTurn_ = false;
      onChanged();
      return this;
    }

    private boolean end_ ;
    /**
     * <pre>
     * 游戏是否结束
     * </pre>
     *
     * <code>bool end = 8;</code>
     * @return The end.
     */
    public boolean getEnd() {
      return end_;
    }
    /**
     * <pre>
     * 游戏是否结束
     * </pre>
     *
     * <code>bool end = 8;</code>
     * @param value The end to set.
     * @return This builder for chaining.
     */
    public Builder setEnd(boolean value) {
      
      end_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 游戏是否结束
     * </pre>
     *
     * <code>bool end = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnd() {
      
      end_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message.FsGameStatusRes)
  }

  // @@protoc_insertion_point(class_scope:Message.FsGameStatusRes)
  private static final proto.FsGameStatusRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.FsGameStatusRes();
  }

  public static proto.FsGameStatusRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FsGameStatusRes>
      PARSER = new com.google.protobuf.AbstractParser<FsGameStatusRes>() {
    @java.lang.Override
    public FsGameStatusRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FsGameStatusRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FsGameStatusRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FsGameStatusRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.FsGameStatusRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

