// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

/**
 * <pre>
 * 游戏开始推送 msgNo:-202
 * </pre>
 *
 * Protobuf type {@code Message.FsGameStartPush}
 */
public  final class FsGameStartPush extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message.FsGameStartPush)
    FsGameStartPushOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FsGameStartPush.newBuilder() to construct.
  private FsGameStartPush(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FsGameStartPush() {
    side_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FsGameStartPush();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FsGameStartPush(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            side_ = rawValue;
            break;
          }
          case 16: {

            startTime_ = input.readInt64();
            break;
          }
          case 24: {

            roundTime_ = input.readInt64();
            break;
          }
          case 40: {

            revertCount_ = input.readInt32();
            break;
          }
          case 48: {

            revertTime_ = input.readInt64();
            break;
          }
          case 56: {

            surrenderRound_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Gobang.internal_static_Message_FsGameStartPush_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Gobang.internal_static_Message_FsGameStartPush_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.FsGameStartPush.class, proto.FsGameStartPush.Builder.class);
  }

  public static final int SIDE_FIELD_NUMBER = 1;
  private int side_;
  /**
   * <pre>
   * 黑子，白子
   * </pre>
   *
   * <code>.Message.Side side = 1;</code>
   * @return The enum numeric value on the wire for side.
   */
  public int getSideValue() {
    return side_;
  }
  /**
   * <pre>
   * 黑子，白子
   * </pre>
   *
   * <code>.Message.Side side = 1;</code>
   * @return The side.
   */
  public proto.Side getSide() {
    @SuppressWarnings("deprecation")
    proto.Side result = proto.Side.valueOf(side_);
    return result == null ? proto.Side.UNRECOGNIZED : result;
  }

  public static final int STARTTIME_FIELD_NUMBER = 2;
  private long startTime_;
  /**
   * <pre>
   * 开始时间 ms
   * </pre>
   *
   * <code>int64 startTime = 2;</code>
   * @return The startTime.
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int ROUNDTIME_FIELD_NUMBER = 3;
  private long roundTime_;
  /**
   * <pre>
   * 回合时间 ms
   * </pre>
   *
   * <code>int64 roundTime = 3;</code>
   * @return The roundTime.
   */
  public long getRoundTime() {
    return roundTime_;
  }

  public static final int REVERTCOUNT_FIELD_NUMBER = 5;
  private int revertCount_;
  /**
   * <pre>
   * 可悔棋次数
   * </pre>
   *
   * <code>int32 revertCount = 5;</code>
   * @return The revertCount.
   */
  public int getRevertCount() {
    return revertCount_;
  }

  public static final int REVERTTIME_FIELD_NUMBER = 6;
  private long revertTime_;
  /**
   * <pre>
   * 悔棋时间
   * </pre>
   *
   * <code>int64 revertTime = 6;</code>
   * @return The revertTime.
   */
  public long getRevertTime() {
    return revertTime_;
  }

  public static final int SURRENDERROUND_FIELD_NUMBER = 7;
  private int surrenderRound_;
  /**
   * <pre>
   * 认输回合
   * </pre>
   *
   * <code>int32 surrenderRound = 7;</code>
   * @return The surrenderRound.
   */
  public int getSurrenderRound() {
    return surrenderRound_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (side_ != proto.Side.NONE.getNumber()) {
      output.writeEnum(1, side_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(2, startTime_);
    }
    if (roundTime_ != 0L) {
      output.writeInt64(3, roundTime_);
    }
    if (revertCount_ != 0) {
      output.writeInt32(5, revertCount_);
    }
    if (revertTime_ != 0L) {
      output.writeInt64(6, revertTime_);
    }
    if (surrenderRound_ != 0) {
      output.writeInt32(7, surrenderRound_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (side_ != proto.Side.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, side_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, startTime_);
    }
    if (roundTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, roundTime_);
    }
    if (revertCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, revertCount_);
    }
    if (revertTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, revertTime_);
    }
    if (surrenderRound_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, surrenderRound_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.FsGameStartPush)) {
      return super.equals(obj);
    }
    proto.FsGameStartPush other = (proto.FsGameStartPush) obj;

    if (side_ != other.side_) return false;
    if (getStartTime()
        != other.getStartTime()) return false;
    if (getRoundTime()
        != other.getRoundTime()) return false;
    if (getRevertCount()
        != other.getRevertCount()) return false;
    if (getRevertTime()
        != other.getRevertTime()) return false;
    if (getSurrenderRound()
        != other.getSurrenderRound()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIDE_FIELD_NUMBER;
    hash = (53 * hash) + side_;
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + ROUNDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRoundTime());
    hash = (37 * hash) + REVERTCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRevertCount();
    hash = (37 * hash) + REVERTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRevertTime());
    hash = (37 * hash) + SURRENDERROUND_FIELD_NUMBER;
    hash = (53 * hash) + getSurrenderRound();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.FsGameStartPush parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsGameStartPush parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsGameStartPush parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsGameStartPush parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsGameStartPush parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsGameStartPush parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsGameStartPush parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.FsGameStartPush parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.FsGameStartPush parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.FsGameStartPush parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.FsGameStartPush parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.FsGameStartPush parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.FsGameStartPush prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 游戏开始推送 msgNo:-202
   * </pre>
   *
   * Protobuf type {@code Message.FsGameStartPush}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message.FsGameStartPush)
      proto.FsGameStartPushOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Gobang.internal_static_Message_FsGameStartPush_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Gobang.internal_static_Message_FsGameStartPush_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.FsGameStartPush.class, proto.FsGameStartPush.Builder.class);
    }

    // Construct using proto.FsGameStartPush.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      side_ = 0;

      startTime_ = 0L;

      roundTime_ = 0L;

      revertCount_ = 0;

      revertTime_ = 0L;

      surrenderRound_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Gobang.internal_static_Message_FsGameStartPush_descriptor;
    }

    @java.lang.Override
    public proto.FsGameStartPush getDefaultInstanceForType() {
      return proto.FsGameStartPush.getDefaultInstance();
    }

    @java.lang.Override
    public proto.FsGameStartPush build() {
      proto.FsGameStartPush result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.FsGameStartPush buildPartial() {
      proto.FsGameStartPush result = new proto.FsGameStartPush(this);
      result.side_ = side_;
      result.startTime_ = startTime_;
      result.roundTime_ = roundTime_;
      result.revertCount_ = revertCount_;
      result.revertTime_ = revertTime_;
      result.surrenderRound_ = surrenderRound_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.FsGameStartPush) {
        return mergeFrom((proto.FsGameStartPush)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.FsGameStartPush other) {
      if (other == proto.FsGameStartPush.getDefaultInstance()) return this;
      if (other.side_ != 0) {
        setSideValue(other.getSideValue());
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getRoundTime() != 0L) {
        setRoundTime(other.getRoundTime());
      }
      if (other.getRevertCount() != 0) {
        setRevertCount(other.getRevertCount());
      }
      if (other.getRevertTime() != 0L) {
        setRevertTime(other.getRevertTime());
      }
      if (other.getSurrenderRound() != 0) {
        setSurrenderRound(other.getSurrenderRound());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.FsGameStartPush parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.FsGameStartPush) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int side_ = 0;
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @return The enum numeric value on the wire for side.
     */
    public int getSideValue() {
      return side_;
    }
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @param value The enum numeric value on the wire for side to set.
     * @return This builder for chaining.
     */
    public Builder setSideValue(int value) {
      side_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @return The side.
     */
    public proto.Side getSide() {
      @SuppressWarnings("deprecation")
      proto.Side result = proto.Side.valueOf(side_);
      return result == null ? proto.Side.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @param value The side to set.
     * @return This builder for chaining.
     */
    public Builder setSide(proto.Side value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      side_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSide() {
      
      side_ = 0;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <pre>
     * 开始时间 ms
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @return The startTime.
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <pre>
     * 开始时间 ms
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 开始时间 ms
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long roundTime_ ;
    /**
     * <pre>
     * 回合时间 ms
     * </pre>
     *
     * <code>int64 roundTime = 3;</code>
     * @return The roundTime.
     */
    public long getRoundTime() {
      return roundTime_;
    }
    /**
     * <pre>
     * 回合时间 ms
     * </pre>
     *
     * <code>int64 roundTime = 3;</code>
     * @param value The roundTime to set.
     * @return This builder for chaining.
     */
    public Builder setRoundTime(long value) {
      
      roundTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 回合时间 ms
     * </pre>
     *
     * <code>int64 roundTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoundTime() {
      
      roundTime_ = 0L;
      onChanged();
      return this;
    }

    private int revertCount_ ;
    /**
     * <pre>
     * 可悔棋次数
     * </pre>
     *
     * <code>int32 revertCount = 5;</code>
     * @return The revertCount.
     */
    public int getRevertCount() {
      return revertCount_;
    }
    /**
     * <pre>
     * 可悔棋次数
     * </pre>
     *
     * <code>int32 revertCount = 5;</code>
     * @param value The revertCount to set.
     * @return This builder for chaining.
     */
    public Builder setRevertCount(int value) {
      
      revertCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 可悔棋次数
     * </pre>
     *
     * <code>int32 revertCount = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevertCount() {
      
      revertCount_ = 0;
      onChanged();
      return this;
    }

    private long revertTime_ ;
    /**
     * <pre>
     * 悔棋时间
     * </pre>
     *
     * <code>int64 revertTime = 6;</code>
     * @return The revertTime.
     */
    public long getRevertTime() {
      return revertTime_;
    }
    /**
     * <pre>
     * 悔棋时间
     * </pre>
     *
     * <code>int64 revertTime = 6;</code>
     * @param value The revertTime to set.
     * @return This builder for chaining.
     */
    public Builder setRevertTime(long value) {
      
      revertTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 悔棋时间
     * </pre>
     *
     * <code>int64 revertTime = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevertTime() {
      
      revertTime_ = 0L;
      onChanged();
      return this;
    }

    private int surrenderRound_ ;
    /**
     * <pre>
     * 认输回合
     * </pre>
     *
     * <code>int32 surrenderRound = 7;</code>
     * @return The surrenderRound.
     */
    public int getSurrenderRound() {
      return surrenderRound_;
    }
    /**
     * <pre>
     * 认输回合
     * </pre>
     *
     * <code>int32 surrenderRound = 7;</code>
     * @param value The surrenderRound to set.
     * @return This builder for chaining.
     */
    public Builder setSurrenderRound(int value) {
      
      surrenderRound_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 认输回合
     * </pre>
     *
     * <code>int32 surrenderRound = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSurrenderRound() {
      
      surrenderRound_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message.FsGameStartPush)
  }

  // @@protoc_insertion_point(class_scope:Message.FsGameStartPush)
  private static final proto.FsGameStartPush DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.FsGameStartPush();
  }

  public static proto.FsGameStartPush getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FsGameStartPush>
      PARSER = new com.google.protobuf.AbstractParser<FsGameStartPush>() {
    @java.lang.Override
    public FsGameStartPush parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FsGameStartPush(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FsGameStartPush> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FsGameStartPush> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.FsGameStartPush getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

