// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsGameStatusReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsGameStatusReq)
    com.google.protobuf.MessageOrBuilder {
}
