// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

/**
 * <pre>
 * 游戏结束推送  msgNo:-205
 * </pre>
 *
 * Protobuf type {@code Message.FsGameOverPush}
 */
public  final class FsGameOverPush extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message.FsGameOverPush)
    FsGameOverPushOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FsGameOverPush.newBuilder() to construct.
  private FsGameOverPush(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FsGameOverPush() {
    step_ = "";
    rewardPack_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FsGameOverPush();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FsGameOverPush(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            win_ = input.readBool();
            break;
          }
          case 16: {

            stepUp_ = input.readInt32();
            break;
          }
          case 24: {

            star_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            step_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              rewardPack_ = new java.util.ArrayList<proto.Reward>();
              mutable_bitField0_ |= 0x00000001;
            }
            rewardPack_.add(
                input.readMessage(proto.Reward.parser(), extensionRegistry));
            break;
          }
          case 48: {

            gold_ = input.readInt32();
            break;
          }
          case 56: {

            goldLimit_ = input.readInt32();
            break;
          }
          case 64: {

            goldAdded_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        rewardPack_ = java.util.Collections.unmodifiableList(rewardPack_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Gobang.internal_static_Message_FsGameOverPush_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Gobang.internal_static_Message_FsGameOverPush_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.FsGameOverPush.class, proto.FsGameOverPush.Builder.class);
  }

  public static final int WIN_FIELD_NUMBER = 1;
  private boolean win_;
  /**
   * <pre>
   * 是否胜利
   * </pre>
   *
   * <code>bool win = 1;</code>
   * @return The win.
   */
  public boolean getWin() {
    return win_;
  }

  public static final int STEPUP_FIELD_NUMBER = 2;
  private int stepUp_;
  /**
   * <pre>
   * -1 段位下降， 0 段位不变， 1：段位提升
   * </pre>
   *
   * <code>int32 stepUp = 2;</code>
   * @return The stepUp.
   */
  public int getStepUp() {
    return stepUp_;
  }

  public static final int STAR_FIELD_NUMBER = 3;
  private int star_;
  /**
   * <pre>
   * 星数
   * </pre>
   *
   * <code>int32 star = 3;</code>
   * @return The star.
   */
  public int getStar() {
    return star_;
  }

  public static final int STEP_FIELD_NUMBER = 4;
  private volatile java.lang.Object step_;
  /**
   * <pre>
   * 段位
   * </pre>
   *
   * <code>string step = 4;</code>
   * @return The step.
   */
  public java.lang.String getStep() {
    java.lang.Object ref = step_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      step_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 段位
   * </pre>
   *
   * <code>string step = 4;</code>
   * @return The bytes for step.
   */
  public com.google.protobuf.ByteString
      getStepBytes() {
    java.lang.Object ref = step_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      step_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REWARDPACK_FIELD_NUMBER = 5;
  private java.util.List<proto.Reward> rewardPack_;
  /**
   * <pre>
   * 奖励包
   * </pre>
   *
   * <code>repeated .Message.Reward rewardPack = 5;</code>
   */
  public java.util.List<proto.Reward> getRewardPackList() {
    return rewardPack_;
  }
  /**
   * <pre>
   * 奖励包
   * </pre>
   *
   * <code>repeated .Message.Reward rewardPack = 5;</code>
   */
  public java.util.List<? extends proto.RewardOrBuilder> 
      getRewardPackOrBuilderList() {
    return rewardPack_;
  }
  /**
   * <pre>
   * 奖励包
   * </pre>
   *
   * <code>repeated .Message.Reward rewardPack = 5;</code>
   */
  public int getRewardPackCount() {
    return rewardPack_.size();
  }
  /**
   * <pre>
   * 奖励包
   * </pre>
   *
   * <code>repeated .Message.Reward rewardPack = 5;</code>
   */
  public proto.Reward getRewardPack(int index) {
    return rewardPack_.get(index);
  }
  /**
   * <pre>
   * 奖励包
   * </pre>
   *
   * <code>repeated .Message.Reward rewardPack = 5;</code>
   */
  public proto.RewardOrBuilder getRewardPackOrBuilder(
      int index) {
    return rewardPack_.get(index);
  }

  public static final int GOLD_FIELD_NUMBER = 6;
  private int gold_;
  /**
   * <pre>
   * 获得金币
   * </pre>
   *
   * <code>int32 gold = 6;</code>
   * @return The gold.
   */
  public int getGold() {
    return gold_;
  }

  public static final int GOLDLIMIT_FIELD_NUMBER = 7;
  private int goldLimit_;
  /**
   * <pre>
   * 金币上限
   * </pre>
   *
   * <code>int32 goldLimit = 7;</code>
   * @return The goldLimit.
   */
  public int getGoldLimit() {
    return goldLimit_;
  }

  public static final int GOLDADDED_FIELD_NUMBER = 8;
  private int goldAdded_;
  /**
   * <pre>
   * 今日已获得
   * </pre>
   *
   * <code>int32 goldAdded = 8;</code>
   * @return The goldAdded.
   */
  public int getGoldAdded() {
    return goldAdded_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (win_ != false) {
      output.writeBool(1, win_);
    }
    if (stepUp_ != 0) {
      output.writeInt32(2, stepUp_);
    }
    if (star_ != 0) {
      output.writeInt32(3, star_);
    }
    if (!getStepBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, step_);
    }
    for (int i = 0; i < rewardPack_.size(); i++) {
      output.writeMessage(5, rewardPack_.get(i));
    }
    if (gold_ != 0) {
      output.writeInt32(6, gold_);
    }
    if (goldLimit_ != 0) {
      output.writeInt32(7, goldLimit_);
    }
    if (goldAdded_ != 0) {
      output.writeInt32(8, goldAdded_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (win_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, win_);
    }
    if (stepUp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, stepUp_);
    }
    if (star_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, star_);
    }
    if (!getStepBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, step_);
    }
    for (int i = 0; i < rewardPack_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, rewardPack_.get(i));
    }
    if (gold_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, gold_);
    }
    if (goldLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, goldLimit_);
    }
    if (goldAdded_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, goldAdded_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.FsGameOverPush)) {
      return super.equals(obj);
    }
    proto.FsGameOverPush other = (proto.FsGameOverPush) obj;

    if (getWin()
        != other.getWin()) return false;
    if (getStepUp()
        != other.getStepUp()) return false;
    if (getStar()
        != other.getStar()) return false;
    if (!getStep()
        .equals(other.getStep())) return false;
    if (!getRewardPackList()
        .equals(other.getRewardPackList())) return false;
    if (getGold()
        != other.getGold()) return false;
    if (getGoldLimit()
        != other.getGoldLimit()) return false;
    if (getGoldAdded()
        != other.getGoldAdded()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getWin());
    hash = (37 * hash) + STEPUP_FIELD_NUMBER;
    hash = (53 * hash) + getStepUp();
    hash = (37 * hash) + STAR_FIELD_NUMBER;
    hash = (53 * hash) + getStar();
    hash = (37 * hash) + STEP_FIELD_NUMBER;
    hash = (53 * hash) + getStep().hashCode();
    if (getRewardPackCount() > 0) {
      hash = (37 * hash) + REWARDPACK_FIELD_NUMBER;
      hash = (53 * hash) + getRewardPackList().hashCode();
    }
    hash = (37 * hash) + GOLD_FIELD_NUMBER;
    hash = (53 * hash) + getGold();
    hash = (37 * hash) + GOLDLIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getGoldLimit();
    hash = (37 * hash) + GOLDADDED_FIELD_NUMBER;
    hash = (53 * hash) + getGoldAdded();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.FsGameOverPush parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsGameOverPush parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsGameOverPush parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsGameOverPush parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsGameOverPush parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsGameOverPush parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsGameOverPush parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.FsGameOverPush parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.FsGameOverPush parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.FsGameOverPush parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.FsGameOverPush parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.FsGameOverPush parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.FsGameOverPush prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 游戏结束推送  msgNo:-205
   * </pre>
   *
   * Protobuf type {@code Message.FsGameOverPush}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message.FsGameOverPush)
      proto.FsGameOverPushOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Gobang.internal_static_Message_FsGameOverPush_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Gobang.internal_static_Message_FsGameOverPush_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.FsGameOverPush.class, proto.FsGameOverPush.Builder.class);
    }

    // Construct using proto.FsGameOverPush.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRewardPackFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      win_ = false;

      stepUp_ = 0;

      star_ = 0;

      step_ = "";

      if (rewardPackBuilder_ == null) {
        rewardPack_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        rewardPackBuilder_.clear();
      }
      gold_ = 0;

      goldLimit_ = 0;

      goldAdded_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Gobang.internal_static_Message_FsGameOverPush_descriptor;
    }

    @java.lang.Override
    public proto.FsGameOverPush getDefaultInstanceForType() {
      return proto.FsGameOverPush.getDefaultInstance();
    }

    @java.lang.Override
    public proto.FsGameOverPush build() {
      proto.FsGameOverPush result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.FsGameOverPush buildPartial() {
      proto.FsGameOverPush result = new proto.FsGameOverPush(this);
      int from_bitField0_ = bitField0_;
      result.win_ = win_;
      result.stepUp_ = stepUp_;
      result.star_ = star_;
      result.step_ = step_;
      if (rewardPackBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          rewardPack_ = java.util.Collections.unmodifiableList(rewardPack_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rewardPack_ = rewardPack_;
      } else {
        result.rewardPack_ = rewardPackBuilder_.build();
      }
      result.gold_ = gold_;
      result.goldLimit_ = goldLimit_;
      result.goldAdded_ = goldAdded_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.FsGameOverPush) {
        return mergeFrom((proto.FsGameOverPush)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.FsGameOverPush other) {
      if (other == proto.FsGameOverPush.getDefaultInstance()) return this;
      if (other.getWin() != false) {
        setWin(other.getWin());
      }
      if (other.getStepUp() != 0) {
        setStepUp(other.getStepUp());
      }
      if (other.getStar() != 0) {
        setStar(other.getStar());
      }
      if (!other.getStep().isEmpty()) {
        step_ = other.step_;
        onChanged();
      }
      if (rewardPackBuilder_ == null) {
        if (!other.rewardPack_.isEmpty()) {
          if (rewardPack_.isEmpty()) {
            rewardPack_ = other.rewardPack_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRewardPackIsMutable();
            rewardPack_.addAll(other.rewardPack_);
          }
          onChanged();
        }
      } else {
        if (!other.rewardPack_.isEmpty()) {
          if (rewardPackBuilder_.isEmpty()) {
            rewardPackBuilder_.dispose();
            rewardPackBuilder_ = null;
            rewardPack_ = other.rewardPack_;
            bitField0_ = (bitField0_ & ~0x00000001);
            rewardPackBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRewardPackFieldBuilder() : null;
          } else {
            rewardPackBuilder_.addAllMessages(other.rewardPack_);
          }
        }
      }
      if (other.getGold() != 0) {
        setGold(other.getGold());
      }
      if (other.getGoldLimit() != 0) {
        setGoldLimit(other.getGoldLimit());
      }
      if (other.getGoldAdded() != 0) {
        setGoldAdded(other.getGoldAdded());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.FsGameOverPush parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.FsGameOverPush) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean win_ ;
    /**
     * <pre>
     * 是否胜利
     * </pre>
     *
     * <code>bool win = 1;</code>
     * @return The win.
     */
    public boolean getWin() {
      return win_;
    }
    /**
     * <pre>
     * 是否胜利
     * </pre>
     *
     * <code>bool win = 1;</code>
     * @param value The win to set.
     * @return This builder for chaining.
     */
    public Builder setWin(boolean value) {
      
      win_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否胜利
     * </pre>
     *
     * <code>bool win = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWin() {
      
      win_ = false;
      onChanged();
      return this;
    }

    private int stepUp_ ;
    /**
     * <pre>
     * -1 段位下降， 0 段位不变， 1：段位提升
     * </pre>
     *
     * <code>int32 stepUp = 2;</code>
     * @return The stepUp.
     */
    public int getStepUp() {
      return stepUp_;
    }
    /**
     * <pre>
     * -1 段位下降， 0 段位不变， 1：段位提升
     * </pre>
     *
     * <code>int32 stepUp = 2;</code>
     * @param value The stepUp to set.
     * @return This builder for chaining.
     */
    public Builder setStepUp(int value) {
      
      stepUp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * -1 段位下降， 0 段位不变， 1：段位提升
     * </pre>
     *
     * <code>int32 stepUp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStepUp() {
      
      stepUp_ = 0;
      onChanged();
      return this;
    }

    private int star_ ;
    /**
     * <pre>
     * 星数
     * </pre>
     *
     * <code>int32 star = 3;</code>
     * @return The star.
     */
    public int getStar() {
      return star_;
    }
    /**
     * <pre>
     * 星数
     * </pre>
     *
     * <code>int32 star = 3;</code>
     * @param value The star to set.
     * @return This builder for chaining.
     */
    public Builder setStar(int value) {
      
      star_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 星数
     * </pre>
     *
     * <code>int32 star = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStar() {
      
      star_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object step_ = "";
    /**
     * <pre>
     * 段位
     * </pre>
     *
     * <code>string step = 4;</code>
     * @return The step.
     */
    public java.lang.String getStep() {
      java.lang.Object ref = step_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        step_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 段位
     * </pre>
     *
     * <code>string step = 4;</code>
     * @return The bytes for step.
     */
    public com.google.protobuf.ByteString
        getStepBytes() {
      java.lang.Object ref = step_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        step_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 段位
     * </pre>
     *
     * <code>string step = 4;</code>
     * @param value The step to set.
     * @return This builder for chaining.
     */
    public Builder setStep(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      step_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 段位
     * </pre>
     *
     * <code>string step = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStep() {
      
      step_ = getDefaultInstance().getStep();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 段位
     * </pre>
     *
     * <code>string step = 4;</code>
     * @param value The bytes for step to set.
     * @return This builder for chaining.
     */
    public Builder setStepBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      step_ = value;
      onChanged();
      return this;
    }

    private java.util.List<proto.Reward> rewardPack_ =
      java.util.Collections.emptyList();
    private void ensureRewardPackIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        rewardPack_ = new java.util.ArrayList<proto.Reward>(rewardPack_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.Reward, proto.Reward.Builder, proto.RewardOrBuilder> rewardPackBuilder_;

    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public java.util.List<proto.Reward> getRewardPackList() {
      if (rewardPackBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rewardPack_);
      } else {
        return rewardPackBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public int getRewardPackCount() {
      if (rewardPackBuilder_ == null) {
        return rewardPack_.size();
      } else {
        return rewardPackBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public proto.Reward getRewardPack(int index) {
      if (rewardPackBuilder_ == null) {
        return rewardPack_.get(index);
      } else {
        return rewardPackBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public Builder setRewardPack(
        int index, proto.Reward value) {
      if (rewardPackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRewardPackIsMutable();
        rewardPack_.set(index, value);
        onChanged();
      } else {
        rewardPackBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public Builder setRewardPack(
        int index, proto.Reward.Builder builderForValue) {
      if (rewardPackBuilder_ == null) {
        ensureRewardPackIsMutable();
        rewardPack_.set(index, builderForValue.build());
        onChanged();
      } else {
        rewardPackBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public Builder addRewardPack(proto.Reward value) {
      if (rewardPackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRewardPackIsMutable();
        rewardPack_.add(value);
        onChanged();
      } else {
        rewardPackBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public Builder addRewardPack(
        int index, proto.Reward value) {
      if (rewardPackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRewardPackIsMutable();
        rewardPack_.add(index, value);
        onChanged();
      } else {
        rewardPackBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public Builder addRewardPack(
        proto.Reward.Builder builderForValue) {
      if (rewardPackBuilder_ == null) {
        ensureRewardPackIsMutable();
        rewardPack_.add(builderForValue.build());
        onChanged();
      } else {
        rewardPackBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public Builder addRewardPack(
        int index, proto.Reward.Builder builderForValue) {
      if (rewardPackBuilder_ == null) {
        ensureRewardPackIsMutable();
        rewardPack_.add(index, builderForValue.build());
        onChanged();
      } else {
        rewardPackBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public Builder addAllRewardPack(
        java.lang.Iterable<? extends proto.Reward> values) {
      if (rewardPackBuilder_ == null) {
        ensureRewardPackIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rewardPack_);
        onChanged();
      } else {
        rewardPackBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public Builder clearRewardPack() {
      if (rewardPackBuilder_ == null) {
        rewardPack_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        rewardPackBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public Builder removeRewardPack(int index) {
      if (rewardPackBuilder_ == null) {
        ensureRewardPackIsMutable();
        rewardPack_.remove(index);
        onChanged();
      } else {
        rewardPackBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public proto.Reward.Builder getRewardPackBuilder(
        int index) {
      return getRewardPackFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public proto.RewardOrBuilder getRewardPackOrBuilder(
        int index) {
      if (rewardPackBuilder_ == null) {
        return rewardPack_.get(index);  } else {
        return rewardPackBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public java.util.List<? extends proto.RewardOrBuilder> 
         getRewardPackOrBuilderList() {
      if (rewardPackBuilder_ != null) {
        return rewardPackBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rewardPack_);
      }
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public proto.Reward.Builder addRewardPackBuilder() {
      return getRewardPackFieldBuilder().addBuilder(
          proto.Reward.getDefaultInstance());
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public proto.Reward.Builder addRewardPackBuilder(
        int index) {
      return getRewardPackFieldBuilder().addBuilder(
          index, proto.Reward.getDefaultInstance());
    }
    /**
     * <pre>
     * 奖励包
     * </pre>
     *
     * <code>repeated .Message.Reward rewardPack = 5;</code>
     */
    public java.util.List<proto.Reward.Builder> 
         getRewardPackBuilderList() {
      return getRewardPackFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.Reward, proto.Reward.Builder, proto.RewardOrBuilder> 
        getRewardPackFieldBuilder() {
      if (rewardPackBuilder_ == null) {
        rewardPackBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.Reward, proto.Reward.Builder, proto.RewardOrBuilder>(
                rewardPack_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        rewardPack_ = null;
      }
      return rewardPackBuilder_;
    }

    private int gold_ ;
    /**
     * <pre>
     * 获得金币
     * </pre>
     *
     * <code>int32 gold = 6;</code>
     * @return The gold.
     */
    public int getGold() {
      return gold_;
    }
    /**
     * <pre>
     * 获得金币
     * </pre>
     *
     * <code>int32 gold = 6;</code>
     * @param value The gold to set.
     * @return This builder for chaining.
     */
    public Builder setGold(int value) {
      
      gold_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 获得金币
     * </pre>
     *
     * <code>int32 gold = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGold() {
      
      gold_ = 0;
      onChanged();
      return this;
    }

    private int goldLimit_ ;
    /**
     * <pre>
     * 金币上限
     * </pre>
     *
     * <code>int32 goldLimit = 7;</code>
     * @return The goldLimit.
     */
    public int getGoldLimit() {
      return goldLimit_;
    }
    /**
     * <pre>
     * 金币上限
     * </pre>
     *
     * <code>int32 goldLimit = 7;</code>
     * @param value The goldLimit to set.
     * @return This builder for chaining.
     */
    public Builder setGoldLimit(int value) {
      
      goldLimit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 金币上限
     * </pre>
     *
     * <code>int32 goldLimit = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearGoldLimit() {
      
      goldLimit_ = 0;
      onChanged();
      return this;
    }

    private int goldAdded_ ;
    /**
     * <pre>
     * 今日已获得
     * </pre>
     *
     * <code>int32 goldAdded = 8;</code>
     * @return The goldAdded.
     */
    public int getGoldAdded() {
      return goldAdded_;
    }
    /**
     * <pre>
     * 今日已获得
     * </pre>
     *
     * <code>int32 goldAdded = 8;</code>
     * @param value The goldAdded to set.
     * @return This builder for chaining.
     */
    public Builder setGoldAdded(int value) {
      
      goldAdded_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 今日已获得
     * </pre>
     *
     * <code>int32 goldAdded = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearGoldAdded() {
      
      goldAdded_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message.FsGameOverPush)
  }

  // @@protoc_insertion_point(class_scope:Message.FsGameOverPush)
  private static final proto.FsGameOverPush DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.FsGameOverPush();
  }

  public static proto.FsGameOverPush getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FsGameOverPush>
      PARSER = new com.google.protobuf.AbstractParser<FsGameOverPush>() {
    @java.lang.Override
    public FsGameOverPush parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FsGameOverPush(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FsGameOverPush> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FsGameOverPush> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.FsGameOverPush getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

