// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsGameOverPushOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsGameOverPush)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 是否胜利
   * </pre>
   *
   * <code>bool win = 1;</code>
   * @return The win.
   */
  boolean getWin();

  /**
   * <pre>
   * -1 段位下降， 0 段位不变， 1：段位提升
   * </pre>
   *
   * <code>int32 stepUp = 2;</code>
   * @return The stepUp.
   */
  int getStepUp();

  /**
   * <pre>
   * 星数
   * </pre>
   *
   * <code>int32 star = 3;</code>
   * @return The star.
   */
  int getStar();

  /**
   * <pre>
   * 段位
   * </pre>
   *
   * <code>string step = 4;</code>
   * @return The step.
   */
  java.lang.String getStep();
  /**
   * <pre>
   * 段位
   * </pre>
   *
   * <code>string step = 4;</code>
   * @return The bytes for step.
   */
  com.google.protobuf.ByteString
      getStepBytes();

  /**
   * <pre>
   * 奖励包
   * </pre>
   *
   * <code>repeated .Message.Reward rewardPack = 5;</code>
   */
  java.util.List<proto.Reward> 
      getRewardPackList();
  /**
   * <pre>
   * 奖励包
   * </pre>
   *
   * <code>repeated .Message.Reward rewardPack = 5;</code>
   */
  proto.Reward getRewardPack(int index);
  /**
   * <pre>
   * 奖励包
   * </pre>
   *
   * <code>repeated .Message.Reward rewardPack = 5;</code>
   */
  int getRewardPackCount();
  /**
   * <pre>
   * 奖励包
   * </pre>
   *
   * <code>repeated .Message.Reward rewardPack = 5;</code>
   */
  java.util.List<? extends proto.RewardOrBuilder> 
      getRewardPackOrBuilderList();
  /**
   * <pre>
   * 奖励包
   * </pre>
   *
   * <code>repeated .Message.Reward rewardPack = 5;</code>
   */
  proto.RewardOrBuilder getRewardPackOrBuilder(
      int index);

  /**
   * <pre>
   * 获得金币
   * </pre>
   *
   * <code>int32 gold = 6;</code>
   * @return The gold.
   */
  int getGold();

  /**
   * <pre>
   * 金币上限
   * </pre>
   *
   * <code>int32 goldLimit = 7;</code>
   * @return The goldLimit.
   */
  int getGoldLimit();

  /**
   * <pre>
   * 今日已获得
   * </pre>
   *
   * <code>int32 goldAdded = 8;</code>
   * @return The goldAdded.
   */
  int getGoldAdded();
}
