// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsGameStartReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsGameStartReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *房间id
   * </pre>
   *
   * <code>int64 roomId = 1;</code>
   * @return The roomId.
   */
  long getRoomId();
}
