// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsGameStatusResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsGameStatusRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 黑子，白子
   * </pre>
   *
   * <code>.Message.Side side = 1;</code>
   * @return The enum numeric value on the wire for side.
   */
  int getSideValue();
  /**
   * <pre>
   * 黑子，白子
   * </pre>
   *
   * <code>.Message.Side side = 1;</code>
   * @return The side.
   */
  proto.Side getSide();

  /**
   * <pre>
   * 开始时间 ms
   * </pre>
   *
   * <code>int64 startTime = 2;</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <pre>
   * 回合剩余时间 ms
   * </pre>
   *
   * <code>int64 roundTime = 3;</code>
   * @return The roundTime.
   */
  long getRoundTime();

  /**
   * <pre>
   * 可悔棋次数
   * </pre>
   *
   * <code>int32 revertCount = 5;</code>
   * @return The revertCount.
   */
  int getRevertCount();

  /**
   * <pre>
   * 是否我的回合
   * </pre>
   *
   * <code>bool myTurn = 6;</code>
   * @return The myTurn.
   */
  boolean getMyTurn();

  /**
   * <pre>
   * 游戏是否结束
   * </pre>
   *
   * <code>bool end = 8;</code>
   * @return The end.
   */
  boolean getEnd();
}
