// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsPutResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsPutRes)
    com.google.protobuf.MessageOrBuilder {
}
