// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsRevertResultPushOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsRevertResultPush)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 是否同意悔棋
   * </pre>
   *
   * <code>bool agree = 1;</code>
   * @return The agree.
   */
  boolean getAgree();

  /**
   * <pre>
   * 移除的棋子
   * </pre>
   *
   * <code>repeated .Message.Pos pos = 2;</code>
   */
  java.util.List<proto.Pos> 
      getPosList();
  /**
   * <pre>
   * 移除的棋子
   * </pre>
   *
   * <code>repeated .Message.Pos pos = 2;</code>
   */
  proto.Pos getPos(int index);
  /**
   * <pre>
   * 移除的棋子
   * </pre>
   *
   * <code>repeated .Message.Pos pos = 2;</code>
   */
  int getPosCount();
  /**
   * <pre>
   * 移除的棋子
   * </pre>
   *
   * <code>repeated .Message.Pos pos = 2;</code>
   */
  java.util.List<? extends proto.PosOrBuilder> 
      getPosOrBuilderList();
  /**
   * <pre>
   * 移除的棋子
   * </pre>
   *
   * <code>repeated .Message.Pos pos = 2;</code>
   */
  proto.PosOrBuilder getPosOrBuilder(
      int index);
}
