// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsReEnterGameReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsReEnterGameReq)
    com.google.protobuf.MessageOrBuilder {
}
