// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsRevertAgreeResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsRevertAgreeRes)
    com.google.protobuf.MessageOrBuilder {
}
