// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

/**
 * <pre>
 * 重新进入游戏返回 msgNo: -106
 * </pre>
 *
 * Protobuf type {@code Message.FsReEnterGameRes}
 */
public  final class FsReEnterGameRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message.FsReEnterGameRes)
    FsReEnterGameResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FsReEnterGameRes.newBuilder() to construct.
  private FsReEnterGameRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FsReEnterGameRes() {
    side_ = 0;
    board_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FsReEnterGameRes();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FsReEnterGameRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            side_ = rawValue;
            break;
          }
          case 16: {

            startTime_ = input.readInt64();
            break;
          }
          case 24: {

            roundTime_ = input.readInt64();
            break;
          }
          case 40: {

            revertCount_ = input.readInt32();
            break;
          }
          case 48: {

            myTurn_ = input.readBool();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              board_ = new java.util.ArrayList<proto.Col>();
              mutable_bitField0_ |= 0x00000001;
            }
            board_.add(
                input.readMessage(proto.Col.parser(), extensionRegistry));
            break;
          }
          case 64: {

            revert_ = input.readBool();
            break;
          }
          case 72: {

            revertUid_ = input.readInt64();
            break;
          }
          case 88: {

            end_ = input.readBool();
            break;
          }
          case 96: {

            roundTimeConfig_ = input.readInt64();
            break;
          }
          case 104: {

            revertTimeConfig_ = input.readInt64();
            break;
          }
          case 112: {

            surrenderRemain_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        board_ = java.util.Collections.unmodifiableList(board_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Gobang.internal_static_Message_FsReEnterGameRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Gobang.internal_static_Message_FsReEnterGameRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.FsReEnterGameRes.class, proto.FsReEnterGameRes.Builder.class);
  }

  public static final int SIDE_FIELD_NUMBER = 1;
  private int side_;
  /**
   * <pre>
   * 黑子，白子
   * </pre>
   *
   * <code>.Message.Side side = 1;</code>
   * @return The enum numeric value on the wire for side.
   */
  public int getSideValue() {
    return side_;
  }
  /**
   * <pre>
   * 黑子，白子
   * </pre>
   *
   * <code>.Message.Side side = 1;</code>
   * @return The side.
   */
  public proto.Side getSide() {
    @SuppressWarnings("deprecation")
    proto.Side result = proto.Side.valueOf(side_);
    return result == null ? proto.Side.UNRECOGNIZED : result;
  }

  public static final int STARTTIME_FIELD_NUMBER = 2;
  private long startTime_;
  /**
   * <pre>
   * 开始时间 ms
   * </pre>
   *
   * <code>int64 startTime = 2;</code>
   * @return The startTime.
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int ROUNDTIME_FIELD_NUMBER = 3;
  private long roundTime_;
  /**
   * <pre>
   * 回合剩余时间 ms
   * </pre>
   *
   * <code>int64 roundTime = 3;</code>
   * @return The roundTime.
   */
  public long getRoundTime() {
    return roundTime_;
  }

  public static final int REVERTCOUNT_FIELD_NUMBER = 5;
  private int revertCount_;
  /**
   * <pre>
   * 可悔棋次数
   * </pre>
   *
   * <code>int32 revertCount = 5;</code>
   * @return The revertCount.
   */
  public int getRevertCount() {
    return revertCount_;
  }

  public static final int MYTURN_FIELD_NUMBER = 6;
  private boolean myTurn_;
  /**
   * <pre>
   * 是否我的回合
   * </pre>
   *
   * <code>bool myTurn = 6;</code>
   * @return The myTurn.
   */
  public boolean getMyTurn() {
    return myTurn_;
  }

  public static final int BOARD_FIELD_NUMBER = 7;
  private java.util.List<proto.Col> board_;
  /**
   * <pre>
   * 棋盘
   * </pre>
   *
   * <code>repeated .Message.Col board = 7;</code>
   */
  public java.util.List<proto.Col> getBoardList() {
    return board_;
  }
  /**
   * <pre>
   * 棋盘
   * </pre>
   *
   * <code>repeated .Message.Col board = 7;</code>
   */
  public java.util.List<? extends proto.ColOrBuilder> 
      getBoardOrBuilderList() {
    return board_;
  }
  /**
   * <pre>
   * 棋盘
   * </pre>
   *
   * <code>repeated .Message.Col board = 7;</code>
   */
  public int getBoardCount() {
    return board_.size();
  }
  /**
   * <pre>
   * 棋盘
   * </pre>
   *
   * <code>repeated .Message.Col board = 7;</code>
   */
  public proto.Col getBoard(int index) {
    return board_.get(index);
  }
  /**
   * <pre>
   * 棋盘
   * </pre>
   *
   * <code>repeated .Message.Col board = 7;</code>
   */
  public proto.ColOrBuilder getBoardOrBuilder(
      int index) {
    return board_.get(index);
  }

  public static final int REVERT_FIELD_NUMBER = 8;
  private boolean revert_;
  /**
   * <pre>
   * 是否悔棋中
   * </pre>
   *
   * <code>bool revert = 8;</code>
   * @return The revert.
   */
  public boolean getRevert() {
    return revert_;
  }

  public static final int REVERTUID_FIELD_NUMBER = 9;
  private long revertUid_;
  /**
   * <pre>
   * 悔棋发起人
   * </pre>
   *
   * <code>int64 revertUid = 9;</code>
   * @return The revertUid.
   */
  public long getRevertUid() {
    return revertUid_;
  }

  public static final int END_FIELD_NUMBER = 11;
  private boolean end_;
  /**
   * <pre>
   * 游戏是否结束
   * </pre>
   *
   * <code>bool end = 11;</code>
   * @return The end.
   */
  public boolean getEnd() {
    return end_;
  }

  public static final int ROUNDTIMECONFIG_FIELD_NUMBER = 12;
  private long roundTimeConfig_;
  /**
   * <pre>
   * 配置回合时间 ms
   * </pre>
   *
   * <code>int64 roundTimeConfig = 12;</code>
   * @return The roundTimeConfig.
   */
  public long getRoundTimeConfig() {
    return roundTimeConfig_;
  }

  public static final int REVERTTIMECONFIG_FIELD_NUMBER = 13;
  private long revertTimeConfig_;
  /**
   * <pre>
   * 配置悔棋时间
   * </pre>
   *
   * <code>int64 revertTimeConfig = 13;</code>
   * @return The revertTimeConfig.
   */
  public long getRevertTimeConfig() {
    return revertTimeConfig_;
  }

  public static final int SURRENDERREMAIN_FIELD_NUMBER = 14;
  private int surrenderRemain_;
  /**
   * <pre>
   *悔棋剩余回合数
   * </pre>
   *
   * <code>int32 surrenderRemain = 14;</code>
   * @return The surrenderRemain.
   */
  public int getSurrenderRemain() {
    return surrenderRemain_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (side_ != proto.Side.NONE.getNumber()) {
      output.writeEnum(1, side_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(2, startTime_);
    }
    if (roundTime_ != 0L) {
      output.writeInt64(3, roundTime_);
    }
    if (revertCount_ != 0) {
      output.writeInt32(5, revertCount_);
    }
    if (myTurn_ != false) {
      output.writeBool(6, myTurn_);
    }
    for (int i = 0; i < board_.size(); i++) {
      output.writeMessage(7, board_.get(i));
    }
    if (revert_ != false) {
      output.writeBool(8, revert_);
    }
    if (revertUid_ != 0L) {
      output.writeInt64(9, revertUid_);
    }
    if (end_ != false) {
      output.writeBool(11, end_);
    }
    if (roundTimeConfig_ != 0L) {
      output.writeInt64(12, roundTimeConfig_);
    }
    if (revertTimeConfig_ != 0L) {
      output.writeInt64(13, revertTimeConfig_);
    }
    if (surrenderRemain_ != 0) {
      output.writeInt32(14, surrenderRemain_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (side_ != proto.Side.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, side_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, startTime_);
    }
    if (roundTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, roundTime_);
    }
    if (revertCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, revertCount_);
    }
    if (myTurn_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, myTurn_);
    }
    for (int i = 0; i < board_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, board_.get(i));
    }
    if (revert_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, revert_);
    }
    if (revertUid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, revertUid_);
    }
    if (end_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, end_);
    }
    if (roundTimeConfig_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, roundTimeConfig_);
    }
    if (revertTimeConfig_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, revertTimeConfig_);
    }
    if (surrenderRemain_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, surrenderRemain_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.FsReEnterGameRes)) {
      return super.equals(obj);
    }
    proto.FsReEnterGameRes other = (proto.FsReEnterGameRes) obj;

    if (side_ != other.side_) return false;
    if (getStartTime()
        != other.getStartTime()) return false;
    if (getRoundTime()
        != other.getRoundTime()) return false;
    if (getRevertCount()
        != other.getRevertCount()) return false;
    if (getMyTurn()
        != other.getMyTurn()) return false;
    if (!getBoardList()
        .equals(other.getBoardList())) return false;
    if (getRevert()
        != other.getRevert()) return false;
    if (getRevertUid()
        != other.getRevertUid()) return false;
    if (getEnd()
        != other.getEnd()) return false;
    if (getRoundTimeConfig()
        != other.getRoundTimeConfig()) return false;
    if (getRevertTimeConfig()
        != other.getRevertTimeConfig()) return false;
    if (getSurrenderRemain()
        != other.getSurrenderRemain()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIDE_FIELD_NUMBER;
    hash = (53 * hash) + side_;
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + ROUNDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRoundTime());
    hash = (37 * hash) + REVERTCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRevertCount();
    hash = (37 * hash) + MYTURN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMyTurn());
    if (getBoardCount() > 0) {
      hash = (37 * hash) + BOARD_FIELD_NUMBER;
      hash = (53 * hash) + getBoardList().hashCode();
    }
    hash = (37 * hash) + REVERT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRevert());
    hash = (37 * hash) + REVERTUID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRevertUid());
    hash = (37 * hash) + END_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnd());
    hash = (37 * hash) + ROUNDTIMECONFIG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRoundTimeConfig());
    hash = (37 * hash) + REVERTTIMECONFIG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRevertTimeConfig());
    hash = (37 * hash) + SURRENDERREMAIN_FIELD_NUMBER;
    hash = (53 * hash) + getSurrenderRemain();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.FsReEnterGameRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsReEnterGameRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsReEnterGameRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsReEnterGameRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsReEnterGameRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsReEnterGameRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsReEnterGameRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.FsReEnterGameRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.FsReEnterGameRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.FsReEnterGameRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.FsReEnterGameRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.FsReEnterGameRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.FsReEnterGameRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 重新进入游戏返回 msgNo: -106
   * </pre>
   *
   * Protobuf type {@code Message.FsReEnterGameRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message.FsReEnterGameRes)
      proto.FsReEnterGameResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Gobang.internal_static_Message_FsReEnterGameRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Gobang.internal_static_Message_FsReEnterGameRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.FsReEnterGameRes.class, proto.FsReEnterGameRes.Builder.class);
    }

    // Construct using proto.FsReEnterGameRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBoardFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      side_ = 0;

      startTime_ = 0L;

      roundTime_ = 0L;

      revertCount_ = 0;

      myTurn_ = false;

      if (boardBuilder_ == null) {
        board_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        boardBuilder_.clear();
      }
      revert_ = false;

      revertUid_ = 0L;

      end_ = false;

      roundTimeConfig_ = 0L;

      revertTimeConfig_ = 0L;

      surrenderRemain_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Gobang.internal_static_Message_FsReEnterGameRes_descriptor;
    }

    @java.lang.Override
    public proto.FsReEnterGameRes getDefaultInstanceForType() {
      return proto.FsReEnterGameRes.getDefaultInstance();
    }

    @java.lang.Override
    public proto.FsReEnterGameRes build() {
      proto.FsReEnterGameRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.FsReEnterGameRes buildPartial() {
      proto.FsReEnterGameRes result = new proto.FsReEnterGameRes(this);
      int from_bitField0_ = bitField0_;
      result.side_ = side_;
      result.startTime_ = startTime_;
      result.roundTime_ = roundTime_;
      result.revertCount_ = revertCount_;
      result.myTurn_ = myTurn_;
      if (boardBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          board_ = java.util.Collections.unmodifiableList(board_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.board_ = board_;
      } else {
        result.board_ = boardBuilder_.build();
      }
      result.revert_ = revert_;
      result.revertUid_ = revertUid_;
      result.end_ = end_;
      result.roundTimeConfig_ = roundTimeConfig_;
      result.revertTimeConfig_ = revertTimeConfig_;
      result.surrenderRemain_ = surrenderRemain_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.FsReEnterGameRes) {
        return mergeFrom((proto.FsReEnterGameRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.FsReEnterGameRes other) {
      if (other == proto.FsReEnterGameRes.getDefaultInstance()) return this;
      if (other.side_ != 0) {
        setSideValue(other.getSideValue());
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getRoundTime() != 0L) {
        setRoundTime(other.getRoundTime());
      }
      if (other.getRevertCount() != 0) {
        setRevertCount(other.getRevertCount());
      }
      if (other.getMyTurn() != false) {
        setMyTurn(other.getMyTurn());
      }
      if (boardBuilder_ == null) {
        if (!other.board_.isEmpty()) {
          if (board_.isEmpty()) {
            board_ = other.board_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBoardIsMutable();
            board_.addAll(other.board_);
          }
          onChanged();
        }
      } else {
        if (!other.board_.isEmpty()) {
          if (boardBuilder_.isEmpty()) {
            boardBuilder_.dispose();
            boardBuilder_ = null;
            board_ = other.board_;
            bitField0_ = (bitField0_ & ~0x00000001);
            boardBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBoardFieldBuilder() : null;
          } else {
            boardBuilder_.addAllMessages(other.board_);
          }
        }
      }
      if (other.getRevert() != false) {
        setRevert(other.getRevert());
      }
      if (other.getRevertUid() != 0L) {
        setRevertUid(other.getRevertUid());
      }
      if (other.getEnd() != false) {
        setEnd(other.getEnd());
      }
      if (other.getRoundTimeConfig() != 0L) {
        setRoundTimeConfig(other.getRoundTimeConfig());
      }
      if (other.getRevertTimeConfig() != 0L) {
        setRevertTimeConfig(other.getRevertTimeConfig());
      }
      if (other.getSurrenderRemain() != 0) {
        setSurrenderRemain(other.getSurrenderRemain());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.FsReEnterGameRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.FsReEnterGameRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int side_ = 0;
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @return The enum numeric value on the wire for side.
     */
    public int getSideValue() {
      return side_;
    }
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @param value The enum numeric value on the wire for side to set.
     * @return This builder for chaining.
     */
    public Builder setSideValue(int value) {
      side_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @return The side.
     */
    public proto.Side getSide() {
      @SuppressWarnings("deprecation")
      proto.Side result = proto.Side.valueOf(side_);
      return result == null ? proto.Side.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @param value The side to set.
     * @return This builder for chaining.
     */
    public Builder setSide(proto.Side value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      side_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 黑子，白子
     * </pre>
     *
     * <code>.Message.Side side = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSide() {
      
      side_ = 0;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <pre>
     * 开始时间 ms
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @return The startTime.
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <pre>
     * 开始时间 ms
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 开始时间 ms
     * </pre>
     *
     * <code>int64 startTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long roundTime_ ;
    /**
     * <pre>
     * 回合剩余时间 ms
     * </pre>
     *
     * <code>int64 roundTime = 3;</code>
     * @return The roundTime.
     */
    public long getRoundTime() {
      return roundTime_;
    }
    /**
     * <pre>
     * 回合剩余时间 ms
     * </pre>
     *
     * <code>int64 roundTime = 3;</code>
     * @param value The roundTime to set.
     * @return This builder for chaining.
     */
    public Builder setRoundTime(long value) {
      
      roundTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 回合剩余时间 ms
     * </pre>
     *
     * <code>int64 roundTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoundTime() {
      
      roundTime_ = 0L;
      onChanged();
      return this;
    }

    private int revertCount_ ;
    /**
     * <pre>
     * 可悔棋次数
     * </pre>
     *
     * <code>int32 revertCount = 5;</code>
     * @return The revertCount.
     */
    public int getRevertCount() {
      return revertCount_;
    }
    /**
     * <pre>
     * 可悔棋次数
     * </pre>
     *
     * <code>int32 revertCount = 5;</code>
     * @param value The revertCount to set.
     * @return This builder for chaining.
     */
    public Builder setRevertCount(int value) {
      
      revertCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 可悔棋次数
     * </pre>
     *
     * <code>int32 revertCount = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevertCount() {
      
      revertCount_ = 0;
      onChanged();
      return this;
    }

    private boolean myTurn_ ;
    /**
     * <pre>
     * 是否我的回合
     * </pre>
     *
     * <code>bool myTurn = 6;</code>
     * @return The myTurn.
     */
    public boolean getMyTurn() {
      return myTurn_;
    }
    /**
     * <pre>
     * 是否我的回合
     * </pre>
     *
     * <code>bool myTurn = 6;</code>
     * @param value The myTurn to set.
     * @return This builder for chaining.
     */
    public Builder setMyTurn(boolean value) {
      
      myTurn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否我的回合
     * </pre>
     *
     * <code>bool myTurn = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMyTurn() {
      
      myTurn_ = false;
      onChanged();
      return this;
    }

    private java.util.List<proto.Col> board_ =
      java.util.Collections.emptyList();
    private void ensureBoardIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        board_ = new java.util.ArrayList<proto.Col>(board_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.Col, proto.Col.Builder, proto.ColOrBuilder> boardBuilder_;

    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public java.util.List<proto.Col> getBoardList() {
      if (boardBuilder_ == null) {
        return java.util.Collections.unmodifiableList(board_);
      } else {
        return boardBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public int getBoardCount() {
      if (boardBuilder_ == null) {
        return board_.size();
      } else {
        return boardBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public proto.Col getBoard(int index) {
      if (boardBuilder_ == null) {
        return board_.get(index);
      } else {
        return boardBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public Builder setBoard(
        int index, proto.Col value) {
      if (boardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBoardIsMutable();
        board_.set(index, value);
        onChanged();
      } else {
        boardBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public Builder setBoard(
        int index, proto.Col.Builder builderForValue) {
      if (boardBuilder_ == null) {
        ensureBoardIsMutable();
        board_.set(index, builderForValue.build());
        onChanged();
      } else {
        boardBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public Builder addBoard(proto.Col value) {
      if (boardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBoardIsMutable();
        board_.add(value);
        onChanged();
      } else {
        boardBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public Builder addBoard(
        int index, proto.Col value) {
      if (boardBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBoardIsMutable();
        board_.add(index, value);
        onChanged();
      } else {
        boardBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public Builder addBoard(
        proto.Col.Builder builderForValue) {
      if (boardBuilder_ == null) {
        ensureBoardIsMutable();
        board_.add(builderForValue.build());
        onChanged();
      } else {
        boardBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public Builder addBoard(
        int index, proto.Col.Builder builderForValue) {
      if (boardBuilder_ == null) {
        ensureBoardIsMutable();
        board_.add(index, builderForValue.build());
        onChanged();
      } else {
        boardBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public Builder addAllBoard(
        java.lang.Iterable<? extends proto.Col> values) {
      if (boardBuilder_ == null) {
        ensureBoardIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, board_);
        onChanged();
      } else {
        boardBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public Builder clearBoard() {
      if (boardBuilder_ == null) {
        board_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        boardBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public Builder removeBoard(int index) {
      if (boardBuilder_ == null) {
        ensureBoardIsMutable();
        board_.remove(index);
        onChanged();
      } else {
        boardBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public proto.Col.Builder getBoardBuilder(
        int index) {
      return getBoardFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public proto.ColOrBuilder getBoardOrBuilder(
        int index) {
      if (boardBuilder_ == null) {
        return board_.get(index);  } else {
        return boardBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public java.util.List<? extends proto.ColOrBuilder> 
         getBoardOrBuilderList() {
      if (boardBuilder_ != null) {
        return boardBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(board_);
      }
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public proto.Col.Builder addBoardBuilder() {
      return getBoardFieldBuilder().addBuilder(
          proto.Col.getDefaultInstance());
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public proto.Col.Builder addBoardBuilder(
        int index) {
      return getBoardFieldBuilder().addBuilder(
          index, proto.Col.getDefaultInstance());
    }
    /**
     * <pre>
     * 棋盘
     * </pre>
     *
     * <code>repeated .Message.Col board = 7;</code>
     */
    public java.util.List<proto.Col.Builder> 
         getBoardBuilderList() {
      return getBoardFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.Col, proto.Col.Builder, proto.ColOrBuilder> 
        getBoardFieldBuilder() {
      if (boardBuilder_ == null) {
        boardBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.Col, proto.Col.Builder, proto.ColOrBuilder>(
                board_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        board_ = null;
      }
      return boardBuilder_;
    }

    private boolean revert_ ;
    /**
     * <pre>
     * 是否悔棋中
     * </pre>
     *
     * <code>bool revert = 8;</code>
     * @return The revert.
     */
    public boolean getRevert() {
      return revert_;
    }
    /**
     * <pre>
     * 是否悔棋中
     * </pre>
     *
     * <code>bool revert = 8;</code>
     * @param value The revert to set.
     * @return This builder for chaining.
     */
    public Builder setRevert(boolean value) {
      
      revert_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否悔棋中
     * </pre>
     *
     * <code>bool revert = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevert() {
      
      revert_ = false;
      onChanged();
      return this;
    }

    private long revertUid_ ;
    /**
     * <pre>
     * 悔棋发起人
     * </pre>
     *
     * <code>int64 revertUid = 9;</code>
     * @return The revertUid.
     */
    public long getRevertUid() {
      return revertUid_;
    }
    /**
     * <pre>
     * 悔棋发起人
     * </pre>
     *
     * <code>int64 revertUid = 9;</code>
     * @param value The revertUid to set.
     * @return This builder for chaining.
     */
    public Builder setRevertUid(long value) {
      
      revertUid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 悔棋发起人
     * </pre>
     *
     * <code>int64 revertUid = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevertUid() {
      
      revertUid_ = 0L;
      onChanged();
      return this;
    }

    private boolean end_ ;
    /**
     * <pre>
     * 游戏是否结束
     * </pre>
     *
     * <code>bool end = 11;</code>
     * @return The end.
     */
    public boolean getEnd() {
      return end_;
    }
    /**
     * <pre>
     * 游戏是否结束
     * </pre>
     *
     * <code>bool end = 11;</code>
     * @param value The end to set.
     * @return This builder for chaining.
     */
    public Builder setEnd(boolean value) {
      
      end_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 游戏是否结束
     * </pre>
     *
     * <code>bool end = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnd() {
      
      end_ = false;
      onChanged();
      return this;
    }

    private long roundTimeConfig_ ;
    /**
     * <pre>
     * 配置回合时间 ms
     * </pre>
     *
     * <code>int64 roundTimeConfig = 12;</code>
     * @return The roundTimeConfig.
     */
    public long getRoundTimeConfig() {
      return roundTimeConfig_;
    }
    /**
     * <pre>
     * 配置回合时间 ms
     * </pre>
     *
     * <code>int64 roundTimeConfig = 12;</code>
     * @param value The roundTimeConfig to set.
     * @return This builder for chaining.
     */
    public Builder setRoundTimeConfig(long value) {
      
      roundTimeConfig_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 配置回合时间 ms
     * </pre>
     *
     * <code>int64 roundTimeConfig = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoundTimeConfig() {
      
      roundTimeConfig_ = 0L;
      onChanged();
      return this;
    }

    private long revertTimeConfig_ ;
    /**
     * <pre>
     * 配置悔棋时间
     * </pre>
     *
     * <code>int64 revertTimeConfig = 13;</code>
     * @return The revertTimeConfig.
     */
    public long getRevertTimeConfig() {
      return revertTimeConfig_;
    }
    /**
     * <pre>
     * 配置悔棋时间
     * </pre>
     *
     * <code>int64 revertTimeConfig = 13;</code>
     * @param value The revertTimeConfig to set.
     * @return This builder for chaining.
     */
    public Builder setRevertTimeConfig(long value) {
      
      revertTimeConfig_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 配置悔棋时间
     * </pre>
     *
     * <code>int64 revertTimeConfig = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevertTimeConfig() {
      
      revertTimeConfig_ = 0L;
      onChanged();
      return this;
    }

    private int surrenderRemain_ ;
    /**
     * <pre>
     *悔棋剩余回合数
     * </pre>
     *
     * <code>int32 surrenderRemain = 14;</code>
     * @return The surrenderRemain.
     */
    public int getSurrenderRemain() {
      return surrenderRemain_;
    }
    /**
     * <pre>
     *悔棋剩余回合数
     * </pre>
     *
     * <code>int32 surrenderRemain = 14;</code>
     * @param value The surrenderRemain to set.
     * @return This builder for chaining.
     */
    public Builder setSurrenderRemain(int value) {
      
      surrenderRemain_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *悔棋剩余回合数
     * </pre>
     *
     * <code>int32 surrenderRemain = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearSurrenderRemain() {
      
      surrenderRemain_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message.FsReEnterGameRes)
  }

  // @@protoc_insertion_point(class_scope:Message.FsReEnterGameRes)
  private static final proto.FsReEnterGameRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.FsReEnterGameRes();
  }

  public static proto.FsReEnterGameRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FsReEnterGameRes>
      PARSER = new com.google.protobuf.AbstractParser<FsReEnterGameRes>() {
    @java.lang.Override
    public FsReEnterGameRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FsReEnterGameRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FsReEnterGameRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FsReEnterGameRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.FsReEnterGameRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

