// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

/**
 * <pre>
 * 悔棋结果推送  msgNo:-204
 * </pre>
 *
 * Protobuf type {@code Message.FsRevertResultPush}
 */
public  final class FsRevertResultPush extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message.FsRevertResultPush)
    FsRevertResultPushOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FsRevertResultPush.newBuilder() to construct.
  private FsRevertResultPush(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FsRevertResultPush() {
    pos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FsRevertResultPush();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FsRevertResultPush(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            agree_ = input.readBool();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              pos_ = new java.util.ArrayList<proto.Pos>();
              mutable_bitField0_ |= 0x00000001;
            }
            pos_.add(
                input.readMessage(proto.Pos.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        pos_ = java.util.Collections.unmodifiableList(pos_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Gobang.internal_static_Message_FsRevertResultPush_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Gobang.internal_static_Message_FsRevertResultPush_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.FsRevertResultPush.class, proto.FsRevertResultPush.Builder.class);
  }

  public static final int AGREE_FIELD_NUMBER = 1;
  private boolean agree_;
  /**
   * <pre>
   * 是否同意悔棋
   * </pre>
   *
   * <code>bool agree = 1;</code>
   * @return The agree.
   */
  public boolean getAgree() {
    return agree_;
  }

  public static final int POS_FIELD_NUMBER = 2;
  private java.util.List<proto.Pos> pos_;
  /**
   * <pre>
   * 移除的棋子
   * </pre>
   *
   * <code>repeated .Message.Pos pos = 2;</code>
   */
  public java.util.List<proto.Pos> getPosList() {
    return pos_;
  }
  /**
   * <pre>
   * 移除的棋子
   * </pre>
   *
   * <code>repeated .Message.Pos pos = 2;</code>
   */
  public java.util.List<? extends proto.PosOrBuilder> 
      getPosOrBuilderList() {
    return pos_;
  }
  /**
   * <pre>
   * 移除的棋子
   * </pre>
   *
   * <code>repeated .Message.Pos pos = 2;</code>
   */
  public int getPosCount() {
    return pos_.size();
  }
  /**
   * <pre>
   * 移除的棋子
   * </pre>
   *
   * <code>repeated .Message.Pos pos = 2;</code>
   */
  public proto.Pos getPos(int index) {
    return pos_.get(index);
  }
  /**
   * <pre>
   * 移除的棋子
   * </pre>
   *
   * <code>repeated .Message.Pos pos = 2;</code>
   */
  public proto.PosOrBuilder getPosOrBuilder(
      int index) {
    return pos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (agree_ != false) {
      output.writeBool(1, agree_);
    }
    for (int i = 0; i < pos_.size(); i++) {
      output.writeMessage(2, pos_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (agree_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, agree_);
    }
    for (int i = 0; i < pos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, pos_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.FsRevertResultPush)) {
      return super.equals(obj);
    }
    proto.FsRevertResultPush other = (proto.FsRevertResultPush) obj;

    if (getAgree()
        != other.getAgree()) return false;
    if (!getPosList()
        .equals(other.getPosList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGREE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAgree());
    if (getPosCount() > 0) {
      hash = (37 * hash) + POS_FIELD_NUMBER;
      hash = (53 * hash) + getPosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.FsRevertResultPush parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsRevertResultPush parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsRevertResultPush parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsRevertResultPush parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsRevertResultPush parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.FsRevertResultPush parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.FsRevertResultPush parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.FsRevertResultPush parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.FsRevertResultPush parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.FsRevertResultPush parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.FsRevertResultPush parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.FsRevertResultPush parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.FsRevertResultPush prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 悔棋结果推送  msgNo:-204
   * </pre>
   *
   * Protobuf type {@code Message.FsRevertResultPush}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message.FsRevertResultPush)
      proto.FsRevertResultPushOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Gobang.internal_static_Message_FsRevertResultPush_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Gobang.internal_static_Message_FsRevertResultPush_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.FsRevertResultPush.class, proto.FsRevertResultPush.Builder.class);
    }

    // Construct using proto.FsRevertResultPush.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      agree_ = false;

      if (posBuilder_ == null) {
        pos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        posBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Gobang.internal_static_Message_FsRevertResultPush_descriptor;
    }

    @java.lang.Override
    public proto.FsRevertResultPush getDefaultInstanceForType() {
      return proto.FsRevertResultPush.getDefaultInstance();
    }

    @java.lang.Override
    public proto.FsRevertResultPush build() {
      proto.FsRevertResultPush result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.FsRevertResultPush buildPartial() {
      proto.FsRevertResultPush result = new proto.FsRevertResultPush(this);
      int from_bitField0_ = bitField0_;
      result.agree_ = agree_;
      if (posBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          pos_ = java.util.Collections.unmodifiableList(pos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pos_ = pos_;
      } else {
        result.pos_ = posBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.FsRevertResultPush) {
        return mergeFrom((proto.FsRevertResultPush)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.FsRevertResultPush other) {
      if (other == proto.FsRevertResultPush.getDefaultInstance()) return this;
      if (other.getAgree() != false) {
        setAgree(other.getAgree());
      }
      if (posBuilder_ == null) {
        if (!other.pos_.isEmpty()) {
          if (pos_.isEmpty()) {
            pos_ = other.pos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePosIsMutable();
            pos_.addAll(other.pos_);
          }
          onChanged();
        }
      } else {
        if (!other.pos_.isEmpty()) {
          if (posBuilder_.isEmpty()) {
            posBuilder_.dispose();
            posBuilder_ = null;
            pos_ = other.pos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            posBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPosFieldBuilder() : null;
          } else {
            posBuilder_.addAllMessages(other.pos_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.FsRevertResultPush parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.FsRevertResultPush) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean agree_ ;
    /**
     * <pre>
     * 是否同意悔棋
     * </pre>
     *
     * <code>bool agree = 1;</code>
     * @return The agree.
     */
    public boolean getAgree() {
      return agree_;
    }
    /**
     * <pre>
     * 是否同意悔棋
     * </pre>
     *
     * <code>bool agree = 1;</code>
     * @param value The agree to set.
     * @return This builder for chaining.
     */
    public Builder setAgree(boolean value) {
      
      agree_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否同意悔棋
     * </pre>
     *
     * <code>bool agree = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgree() {
      
      agree_ = false;
      onChanged();
      return this;
    }

    private java.util.List<proto.Pos> pos_ =
      java.util.Collections.emptyList();
    private void ensurePosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        pos_ = new java.util.ArrayList<proto.Pos>(pos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.Pos, proto.Pos.Builder, proto.PosOrBuilder> posBuilder_;

    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public java.util.List<proto.Pos> getPosList() {
      if (posBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pos_);
      } else {
        return posBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public int getPosCount() {
      if (posBuilder_ == null) {
        return pos_.size();
      } else {
        return posBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public proto.Pos getPos(int index) {
      if (posBuilder_ == null) {
        return pos_.get(index);
      } else {
        return posBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public Builder setPos(
        int index, proto.Pos value) {
      if (posBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePosIsMutable();
        pos_.set(index, value);
        onChanged();
      } else {
        posBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public Builder setPos(
        int index, proto.Pos.Builder builderForValue) {
      if (posBuilder_ == null) {
        ensurePosIsMutable();
        pos_.set(index, builderForValue.build());
        onChanged();
      } else {
        posBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public Builder addPos(proto.Pos value) {
      if (posBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePosIsMutable();
        pos_.add(value);
        onChanged();
      } else {
        posBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public Builder addPos(
        int index, proto.Pos value) {
      if (posBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePosIsMutable();
        pos_.add(index, value);
        onChanged();
      } else {
        posBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public Builder addPos(
        proto.Pos.Builder builderForValue) {
      if (posBuilder_ == null) {
        ensurePosIsMutable();
        pos_.add(builderForValue.build());
        onChanged();
      } else {
        posBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public Builder addPos(
        int index, proto.Pos.Builder builderForValue) {
      if (posBuilder_ == null) {
        ensurePosIsMutable();
        pos_.add(index, builderForValue.build());
        onChanged();
      } else {
        posBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public Builder addAllPos(
        java.lang.Iterable<? extends proto.Pos> values) {
      if (posBuilder_ == null) {
        ensurePosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pos_);
        onChanged();
      } else {
        posBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public Builder clearPos() {
      if (posBuilder_ == null) {
        pos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        posBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public Builder removePos(int index) {
      if (posBuilder_ == null) {
        ensurePosIsMutable();
        pos_.remove(index);
        onChanged();
      } else {
        posBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public proto.Pos.Builder getPosBuilder(
        int index) {
      return getPosFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public proto.PosOrBuilder getPosOrBuilder(
        int index) {
      if (posBuilder_ == null) {
        return pos_.get(index);  } else {
        return posBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public java.util.List<? extends proto.PosOrBuilder> 
         getPosOrBuilderList() {
      if (posBuilder_ != null) {
        return posBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pos_);
      }
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public proto.Pos.Builder addPosBuilder() {
      return getPosFieldBuilder().addBuilder(
          proto.Pos.getDefaultInstance());
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public proto.Pos.Builder addPosBuilder(
        int index) {
      return getPosFieldBuilder().addBuilder(
          index, proto.Pos.getDefaultInstance());
    }
    /**
     * <pre>
     * 移除的棋子
     * </pre>
     *
     * <code>repeated .Message.Pos pos = 2;</code>
     */
    public java.util.List<proto.Pos.Builder> 
         getPosBuilderList() {
      return getPosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.Pos, proto.Pos.Builder, proto.PosOrBuilder> 
        getPosFieldBuilder() {
      if (posBuilder_ == null) {
        posBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.Pos, proto.Pos.Builder, proto.PosOrBuilder>(
                pos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        pos_ = null;
      }
      return posBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message.FsRevertResultPush)
  }

  // @@protoc_insertion_point(class_scope:Message.FsRevertResultPush)
  private static final proto.FsRevertResultPush DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.FsRevertResultPush();
  }

  public static proto.FsRevertResultPush getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FsRevertResultPush>
      PARSER = new com.google.protobuf.AbstractParser<FsRevertResultPush>() {
    @java.lang.Override
    public FsRevertResultPush parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FsRevertResultPush(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FsRevertResultPush> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FsRevertResultPush> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.FsRevertResultPush getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

