// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsRevertAgreeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsRevertAgreeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 是否同意悔棋
   * </pre>
   *
   * <code>bool agree = 1;</code>
   * @return The agree.
   */
  boolean getAgree();
}
