// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsRevertReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsRevertReq)
    com.google.protobuf.MessageOrBuilder {
}
