// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsSurrenderReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsSurrenderReq)
    com.google.protobuf.MessageOrBuilder {
}
