// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface FsSurrenderResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.FsSurrenderRes)
    com.google.protobuf.MessageOrBuilder {
}
