// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Wuziqi.proto

package proto;

public interface RewardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message.Reward)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 奖励id
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * 奖励id
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * 奖励数量
   * </pre>
   *
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  int getCount();
}
