// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fightgame.proto

package proto;

public interface BattlePosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.BattlePos)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>int64 heroId = 3;</code>
   * @return The heroId.
   */
  long getHeroId();
}
