// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fightgame.proto

package proto;

public interface BattleFightResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.BattleFightRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * true成功，false失败
   * </pre>
   *
   * <code>bool result = 1;</code>
   * @return The result.
   */
  boolean getResult();

  /**
   * <pre>
   * 星数
   * </pre>
   *
   * <code>int32 star = 2;</code>
   * @return The star.
   */
  int getStar();
}
