// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fightgame.proto

package proto;

/**
 * Protobuf type {@code proto.BattleFightReq}
 */
public  final class BattleFightReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.BattleFightReq)
    BattleFightReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BattleFightReq.newBuilder() to construct.
  private BattleFightReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BattleFightReq() {
    battlePos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BattleFightReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BattleFightReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              battlePos_ = new java.util.ArrayList<proto.BattlePos>();
              mutable_bitField0_ |= 0x00000001;
            }
            battlePos_.add(
                input.readMessage(proto.BattlePos.parser(), extensionRegistry));
            break;
          }
          case 16: {

            battleId_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        battlePos_ = java.util.Collections.unmodifiableList(battlePos_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Fightgame.internal_static_proto_BattleFightReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Fightgame.internal_static_proto_BattleFightReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.BattleFightReq.class, proto.BattleFightReq.Builder.class);
  }

  public static final int BATTLEPOS_FIELD_NUMBER = 1;
  private java.util.List<proto.BattlePos> battlePos_;
  /**
   * <pre>
   * 玩家阵容
   * </pre>
   *
   * <code>repeated .proto.BattlePos BattlePos = 1;</code>
   */
  public java.util.List<proto.BattlePos> getBattlePosList() {
    return battlePos_;
  }
  /**
   * <pre>
   * 玩家阵容
   * </pre>
   *
   * <code>repeated .proto.BattlePos BattlePos = 1;</code>
   */
  public java.util.List<? extends proto.BattlePosOrBuilder> 
      getBattlePosOrBuilderList() {
    return battlePos_;
  }
  /**
   * <pre>
   * 玩家阵容
   * </pre>
   *
   * <code>repeated .proto.BattlePos BattlePos = 1;</code>
   */
  public int getBattlePosCount() {
    return battlePos_.size();
  }
  /**
   * <pre>
   * 玩家阵容
   * </pre>
   *
   * <code>repeated .proto.BattlePos BattlePos = 1;</code>
   */
  public proto.BattlePos getBattlePos(int index) {
    return battlePos_.get(index);
  }
  /**
   * <pre>
   * 玩家阵容
   * </pre>
   *
   * <code>repeated .proto.BattlePos BattlePos = 1;</code>
   */
  public proto.BattlePosOrBuilder getBattlePosOrBuilder(
      int index) {
    return battlePos_.get(index);
  }

  public static final int BATTLEID_FIELD_NUMBER = 2;
  private long battleId_;
  /**
   * <pre>
   * 敌方阵容Id
   * </pre>
   *
   * <code>int64 battleId = 2;</code>
   * @return The battleId.
   */
  public long getBattleId() {
    return battleId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < battlePos_.size(); i++) {
      output.writeMessage(1, battlePos_.get(i));
    }
    if (battleId_ != 0L) {
      output.writeInt64(2, battleId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < battlePos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, battlePos_.get(i));
    }
    if (battleId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, battleId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.BattleFightReq)) {
      return super.equals(obj);
    }
    proto.BattleFightReq other = (proto.BattleFightReq) obj;

    if (!getBattlePosList()
        .equals(other.getBattlePosList())) return false;
    if (getBattleId()
        != other.getBattleId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBattlePosCount() > 0) {
      hash = (37 * hash) + BATTLEPOS_FIELD_NUMBER;
      hash = (53 * hash) + getBattlePosList().hashCode();
    }
    hash = (37 * hash) + BATTLEID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBattleId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.BattleFightReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.BattleFightReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.BattleFightReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.BattleFightReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.BattleFightReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.BattleFightReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.BattleFightReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.BattleFightReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.BattleFightReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.BattleFightReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.BattleFightReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.BattleFightReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.BattleFightReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.BattleFightReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.BattleFightReq)
      proto.BattleFightReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Fightgame.internal_static_proto_BattleFightReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Fightgame.internal_static_proto_BattleFightReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.BattleFightReq.class, proto.BattleFightReq.Builder.class);
    }

    // Construct using proto.BattleFightReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBattlePosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (battlePosBuilder_ == null) {
        battlePos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        battlePosBuilder_.clear();
      }
      battleId_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Fightgame.internal_static_proto_BattleFightReq_descriptor;
    }

    @java.lang.Override
    public proto.BattleFightReq getDefaultInstanceForType() {
      return proto.BattleFightReq.getDefaultInstance();
    }

    @java.lang.Override
    public proto.BattleFightReq build() {
      proto.BattleFightReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.BattleFightReq buildPartial() {
      proto.BattleFightReq result = new proto.BattleFightReq(this);
      int from_bitField0_ = bitField0_;
      if (battlePosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          battlePos_ = java.util.Collections.unmodifiableList(battlePos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.battlePos_ = battlePos_;
      } else {
        result.battlePos_ = battlePosBuilder_.build();
      }
      result.battleId_ = battleId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.BattleFightReq) {
        return mergeFrom((proto.BattleFightReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.BattleFightReq other) {
      if (other == proto.BattleFightReq.getDefaultInstance()) return this;
      if (battlePosBuilder_ == null) {
        if (!other.battlePos_.isEmpty()) {
          if (battlePos_.isEmpty()) {
            battlePos_ = other.battlePos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBattlePosIsMutable();
            battlePos_.addAll(other.battlePos_);
          }
          onChanged();
        }
      } else {
        if (!other.battlePos_.isEmpty()) {
          if (battlePosBuilder_.isEmpty()) {
            battlePosBuilder_.dispose();
            battlePosBuilder_ = null;
            battlePos_ = other.battlePos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            battlePosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBattlePosFieldBuilder() : null;
          } else {
            battlePosBuilder_.addAllMessages(other.battlePos_);
          }
        }
      }
      if (other.getBattleId() != 0L) {
        setBattleId(other.getBattleId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.BattleFightReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.BattleFightReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<proto.BattlePos> battlePos_ =
      java.util.Collections.emptyList();
    private void ensureBattlePosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        battlePos_ = new java.util.ArrayList<proto.BattlePos>(battlePos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.BattlePos, proto.BattlePos.Builder, proto.BattlePosOrBuilder> battlePosBuilder_;

    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public java.util.List<proto.BattlePos> getBattlePosList() {
      if (battlePosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(battlePos_);
      } else {
        return battlePosBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public int getBattlePosCount() {
      if (battlePosBuilder_ == null) {
        return battlePos_.size();
      } else {
        return battlePosBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public proto.BattlePos getBattlePos(int index) {
      if (battlePosBuilder_ == null) {
        return battlePos_.get(index);
      } else {
        return battlePosBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public Builder setBattlePos(
        int index, proto.BattlePos value) {
      if (battlePosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBattlePosIsMutable();
        battlePos_.set(index, value);
        onChanged();
      } else {
        battlePosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public Builder setBattlePos(
        int index, proto.BattlePos.Builder builderForValue) {
      if (battlePosBuilder_ == null) {
        ensureBattlePosIsMutable();
        battlePos_.set(index, builderForValue.build());
        onChanged();
      } else {
        battlePosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public Builder addBattlePos(proto.BattlePos value) {
      if (battlePosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBattlePosIsMutable();
        battlePos_.add(value);
        onChanged();
      } else {
        battlePosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public Builder addBattlePos(
        int index, proto.BattlePos value) {
      if (battlePosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBattlePosIsMutable();
        battlePos_.add(index, value);
        onChanged();
      } else {
        battlePosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public Builder addBattlePos(
        proto.BattlePos.Builder builderForValue) {
      if (battlePosBuilder_ == null) {
        ensureBattlePosIsMutable();
        battlePos_.add(builderForValue.build());
        onChanged();
      } else {
        battlePosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public Builder addBattlePos(
        int index, proto.BattlePos.Builder builderForValue) {
      if (battlePosBuilder_ == null) {
        ensureBattlePosIsMutable();
        battlePos_.add(index, builderForValue.build());
        onChanged();
      } else {
        battlePosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public Builder addAllBattlePos(
        java.lang.Iterable<? extends proto.BattlePos> values) {
      if (battlePosBuilder_ == null) {
        ensureBattlePosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, battlePos_);
        onChanged();
      } else {
        battlePosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public Builder clearBattlePos() {
      if (battlePosBuilder_ == null) {
        battlePos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        battlePosBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public Builder removeBattlePos(int index) {
      if (battlePosBuilder_ == null) {
        ensureBattlePosIsMutable();
        battlePos_.remove(index);
        onChanged();
      } else {
        battlePosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public proto.BattlePos.Builder getBattlePosBuilder(
        int index) {
      return getBattlePosFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public proto.BattlePosOrBuilder getBattlePosOrBuilder(
        int index) {
      if (battlePosBuilder_ == null) {
        return battlePos_.get(index);  } else {
        return battlePosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public java.util.List<? extends proto.BattlePosOrBuilder> 
         getBattlePosOrBuilderList() {
      if (battlePosBuilder_ != null) {
        return battlePosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(battlePos_);
      }
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public proto.BattlePos.Builder addBattlePosBuilder() {
      return getBattlePosFieldBuilder().addBuilder(
          proto.BattlePos.getDefaultInstance());
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public proto.BattlePos.Builder addBattlePosBuilder(
        int index) {
      return getBattlePosFieldBuilder().addBuilder(
          index, proto.BattlePos.getDefaultInstance());
    }
    /**
     * <pre>
     * 玩家阵容
     * </pre>
     *
     * <code>repeated .proto.BattlePos BattlePos = 1;</code>
     */
    public java.util.List<proto.BattlePos.Builder> 
         getBattlePosBuilderList() {
      return getBattlePosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.BattlePos, proto.BattlePos.Builder, proto.BattlePosOrBuilder> 
        getBattlePosFieldBuilder() {
      if (battlePosBuilder_ == null) {
        battlePosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.BattlePos, proto.BattlePos.Builder, proto.BattlePosOrBuilder>(
                battlePos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        battlePos_ = null;
      }
      return battlePosBuilder_;
    }

    private long battleId_ ;
    /**
     * <pre>
     * 敌方阵容Id
     * </pre>
     *
     * <code>int64 battleId = 2;</code>
     * @return The battleId.
     */
    public long getBattleId() {
      return battleId_;
    }
    /**
     * <pre>
     * 敌方阵容Id
     * </pre>
     *
     * <code>int64 battleId = 2;</code>
     * @param value The battleId to set.
     * @return This builder for chaining.
     */
    public Builder setBattleId(long value) {
      
      battleId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 敌方阵容Id
     * </pre>
     *
     * <code>int64 battleId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBattleId() {
      
      battleId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.BattleFightReq)
  }

  // @@protoc_insertion_point(class_scope:proto.BattleFightReq)
  private static final proto.BattleFightReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.BattleFightReq();
  }

  public static proto.BattleFightReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BattleFightReq>
      PARSER = new com.google.protobuf.AbstractParser<BattleFightReq>() {
    @java.lang.Override
    public BattleFightReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BattleFightReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BattleFightReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BattleFightReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.BattleFightReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

