// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fightgame.proto

package proto;

public interface CreateRoomReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CreateRoomReq)
    com.google.protobuf.MessageOrBuilder {
}
