// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fivestone.proto

package proto;

public interface EnterRoomFvstReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.EnterRoomFvstReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roomId = 1;</code>
   * @return The roomId.
   */
  int getRoomId();
}
