// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fivestone.proto

package proto;

public interface EnterRoomFvstResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.EnterRoomFvstRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 side = 1;</code>
   * @return The side.
   */
  int getSide();
}
