// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package proto;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index = 1;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
