// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fightgame.proto

package proto;

public final class Fightgame {
  private Fightgame() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MoveTel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MoveTel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MoveMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MoveMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EnterRoomReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_EnterRoomReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateRoomReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateRoomReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateRoomRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateRoomRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_JoinRoomReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_JoinRoomReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BattleFightReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_BattleFightReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BattleFightRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_BattleFightRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BattlePos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_BattlePos_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017fightgame.proto\022\005proto\"\037\n\007MoveTel\022\t\n\001x" +
      "\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\"\037\n\007MoveMsg\022\t\n\001x\030\001 \001(\001\022" +
      "\t\n\001y\030\002 \001(\001\"\036\n\014EnterRoomReq\022\016\n\006roomId\030\001 \001" +
      "(\005\"\017\n\rCreateRoomReq\"\037\n\rCreateRoomRes\022\016\n\006" +
      "roomId\030\001 \001(\005\"\035\n\013JoinRoomReq\022\016\n\006roomId\030\001 " +
      "\001(\005\"G\n\016BattleFightReq\022#\n\tBattlePos\030\001 \003(\013" +
      "2\020.proto.BattlePos\022\020\n\010battleId\030\002 \001(\003\".\n\016" +
      "BattleFightRes\022\016\n\006result\030\001 \001(\010\022\014\n\004star\030\002" +
      " \001(\005\"1\n\tBattlePos\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022" +
      "\016\n\006heroId\030\003 \001(\003B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_MoveTel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_MoveTel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MoveTel_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_proto_MoveMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_MoveMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MoveMsg_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_proto_EnterRoomReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_EnterRoomReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_EnterRoomReq_descriptor,
        new java.lang.String[] { "RoomId", });
    internal_static_proto_CreateRoomReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_CreateRoomReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateRoomReq_descriptor,
        new java.lang.String[] { });
    internal_static_proto_CreateRoomRes_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_CreateRoomRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateRoomRes_descriptor,
        new java.lang.String[] { "RoomId", });
    internal_static_proto_JoinRoomReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_JoinRoomReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_JoinRoomReq_descriptor,
        new java.lang.String[] { "RoomId", });
    internal_static_proto_BattleFightReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_BattleFightReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_BattleFightReq_descriptor,
        new java.lang.String[] { "BattlePos", "BattleId", });
    internal_static_proto_BattleFightRes_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_proto_BattleFightRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_BattleFightRes_descriptor,
        new java.lang.String[] { "Result", "Star", });
    internal_static_proto_BattlePos_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_proto_BattlePos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_BattlePos_descriptor,
        new java.lang.String[] { "X", "Y", "HeroId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
