// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fivestone.proto

package proto;

public interface FindRoomReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.FindRoomReq)
    com.google.protobuf.MessageOrBuilder {
}
