// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fivestone.proto

package proto;

public interface FindRoomResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.FindRoomRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 roomId = 1;</code>
   * @return The roomId.
   */
  int getRoomId();

  /**
   * <code>int32 side = 2;</code>
   * @return The side.
   */
  int getSide();
}
