// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fivestone.proto

package proto;

public final class Fivestone {
  private Fivestone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EnterRoomFvstReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_EnterRoomFvstReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EnterRoomFvstRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_EnterRoomFvstRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateRoomFvstReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateRoomFvstReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateRoomFvstRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateRoomFvstRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FindRoomReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FindRoomReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FindRoomRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FindRoomRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ExitRoomReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ExitRoomReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StartGameReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StartGameReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PutKeyFvstReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PutKeyFvstReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PutKeyFvstRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PutKeyFvstRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StartFvstMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StartFvstMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PutKeyFvstMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PutKeyFvstMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GameEndFvstMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GameEndFvstMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017fivestone.proto\022\005proto\"\"\n\020EnterRoomFvs" +
      "tReq\022\016\n\006roomId\030\001 \001(\005\" \n\020EnterRoomFvstRes" +
      "\022\014\n\004side\030\001 \001(\005\"\023\n\021CreateRoomFvstReq\"#\n\021C" +
      "reateRoomFvstRes\022\016\n\006roomId\030\001 \001(\005\"\r\n\013Find" +
      "RoomReq\"+\n\013FindRoomRes\022\016\n\006roomId\030\001 \001(\005\022\014" +
      "\n\004side\030\002 \001(\005\"\r\n\013ExitRoomReq\"\016\n\014StartGame" +
      "Req\"%\n\rPutKeyFvstReq\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001" +
      "(\005\"\034\n\rPutKeyFvstRes\022\013\n\003win\030\001 \001(\010\"\034\n\014Star" +
      "tFvstMsg\022\014\n\004name\030\001 \001(\t\"%\n\rPutKeyFvstMsg\022" +
      "\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\"\035\n\016GameEndFvstMsg\022" +
      "\013\n\003win\030\001 \001(\010B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_EnterRoomFvstReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_EnterRoomFvstReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_EnterRoomFvstReq_descriptor,
        new java.lang.String[] { "RoomId", });
    internal_static_proto_EnterRoomFvstRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_EnterRoomFvstRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_EnterRoomFvstRes_descriptor,
        new java.lang.String[] { "Side", });
    internal_static_proto_CreateRoomFvstReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_CreateRoomFvstReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateRoomFvstReq_descriptor,
        new java.lang.String[] { });
    internal_static_proto_CreateRoomFvstRes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_CreateRoomFvstRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateRoomFvstRes_descriptor,
        new java.lang.String[] { "RoomId", });
    internal_static_proto_FindRoomReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_FindRoomReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FindRoomReq_descriptor,
        new java.lang.String[] { });
    internal_static_proto_FindRoomRes_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_FindRoomRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FindRoomRes_descriptor,
        new java.lang.String[] { "RoomId", "Side", });
    internal_static_proto_ExitRoomReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_ExitRoomReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ExitRoomReq_descriptor,
        new java.lang.String[] { });
    internal_static_proto_StartGameReq_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_proto_StartGameReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StartGameReq_descriptor,
        new java.lang.String[] { });
    internal_static_proto_PutKeyFvstReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_proto_PutKeyFvstReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PutKeyFvstReq_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_proto_PutKeyFvstRes_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_proto_PutKeyFvstRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PutKeyFvstRes_descriptor,
        new java.lang.String[] { "Win", });
    internal_static_proto_StartFvstMsg_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_proto_StartFvstMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StartFvstMsg_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_proto_PutKeyFvstMsg_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_proto_PutKeyFvstMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PutKeyFvstMsg_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_proto_GameEndFvstMsg_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_proto_GameEndFvstMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GameEndFvstMsg_descriptor,
        new java.lang.String[] { "Win", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
