// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fivestone.proto

package proto;

public interface GameEndFvstMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GameEndFvstMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool win = 1;</code>
   * @return The win.
   */
  boolean getWin();
}
