// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package proto;

public interface HbResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.HbRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 time = 1;</code>
   * @return The time.
   */
  long getTime();

  /**
   * <code>string zone = 2;</code>
   * @return The zone.
   */
  java.lang.String getZone();
  /**
   * <code>string zone = 2;</code>
   * @return The bytes for zone.
   */
  com.google.protobuf.ByteString
      getZoneBytes();
}
