// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package proto;

public interface LoginResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.LoginRes)
    com.google.protobuf.MessageOrBuilder {
}
