// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package proto;

public interface LogoutReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.LogoutReq)
    com.google.protobuf.MessageOrBuilder {
}
