// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fightgame.proto

package proto;

public interface MoveTelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MoveTel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();
}
