// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fivestone.proto

package proto;

public interface PutKeyFvstMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PutKeyFvstMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   * @return The y.
   */
  int getY();
}
