// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fivestone.proto

package proto;

public interface PutKeyFvstResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PutKeyFvstRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 是否胜利
   * </pre>
   *
   * <code>bool win = 1;</code>
   * @return The win.
   */
  boolean getWin();
}
