// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package proto;

public interface ServerReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ServerReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 服务器类型,1:gateway 2:app
   * </pre>
   *
   * <code>int32 type = 1;</code>
   * @return The type.
   */
  int getType();

  /**
   * <pre>
   * 唯一标识
   * </pre>
   *
   * <code>string serverId = 2;</code>
   * @return The serverId.
   */
  java.lang.String getServerId();
  /**
   * <pre>
   * 唯一标识
   * </pre>
   *
   * <code>string serverId = 2;</code>
   * @return The bytes for serverId.
   */
  com.google.protobuf.ByteString
      getServerIdBytes();
}
