// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fivestone.proto

package proto;

public interface StartFvstMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.StartFvstMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 对方名称
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * 对方名称
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
