// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package proto;

public interface SuccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Success)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ok = 1;</code>
   * @return The ok.
   */
  java.lang.String getOk();
  /**
   * <code>string ok = 1;</code>
   * @return The bytes for ok.
   */
  com.google.protobuf.ByteString
      getOkBytes();
}
